#!/usr/bin/env bash
# Downloads and builds what the comparisons need, under $WORK (see env.sh):
#   - GMP and MPFR (static), unless the system has their headers,
#   - libieeep1788 (header only) at the commit P1788_COMMIT,
#   - filib++ FILIB_VERSION, unless FILIB_DIR gives an installed one,
#   - PROFIL/BIAS PROFIL_VERSION, from its site (or the archive PROFIL_TGZ),
#     built with its x86-64 Linux configuration,
#   - GAOL, this repository, built with CMake in Release and installed,
#   - the last GAOL of Frédéric Goualard, at the commit GAOL_GOUALARD_COMMIT,
#     with mathlib MATHLIB_VERSION, built with their configure,
# and checks that Solaris Studio's f90 compiles an interval program.
# Everything is compiled by $CC and $CXX with -O3 and $FMA_FLAGS (-mfma, see
# env.sh): GMP, MPFR and PROFIL/BIAS compile with -O2 on their own, and the
# configure of filib++ without any optimization. Each step is skipped when its
# result is already there.
#
# Copyright (c) 2026 ENSTA, France
#
# Created 2026-09-20 by Jordan NININ
set -euo pipefail
source "$(dirname "$0")/env.sh"

mkdir -p "$WORK/src" "$PREFIX"
cd "$WORK/src"

fetch() {  # fetch <url> <file> <sha256>
  [ -f "$2" ] || curl -fsSL -o "$2" "$1"
  echo "$3  $2" | sha256sum -c --quiet - || die "bad checksum for $2"
}

have_system_header() {
  echo "#include <$1>" | "$CC" -E -x c - >/dev/null 2>&1
}

## GMP and MPFR
if [ -f "$PREFIX/include/mpfr.h" ]; then
  echo "== GMP and MPFR: already in $PREFIX"
elif have_system_header gmp.h && have_system_header mpfr.h; then
  echo "== GMP and MPFR: the system's"
  # p1788_cflags adds -I$PREFIX/include, which is harmless
else
  echo "== GMP $GMP_VERSION"
  fetch "https://gmplib.org/download/gmp/gmp-$GMP_VERSION.tar.xz" \
        "gmp-$GMP_VERSION.tar.xz" "$GMP_SHA256"
  rm -rf "gmp-$GMP_VERSION" && tar xf "gmp-$GMP_VERSION.tar.xz"
  (cd "gmp-$GMP_VERSION" &&
   ./configure --prefix="$PREFIX" --libdir="$PREFIX/lib" --disable-shared --enable-static CC="$CC" CFLAGS="-O3 $FMA_FLAGS" > configure.log &&
   make -j"$JOBS" > make.log && make install > install.log)

  echo "== MPFR $MPFR_VERSION"
  fetch "https://www.mpfr.org/mpfr-$MPFR_VERSION/mpfr-$MPFR_VERSION.tar.xz" \
        "mpfr-$MPFR_VERSION.tar.xz" "$MPFR_SHA256"
  rm -rf "mpfr-$MPFR_VERSION" && tar xf "mpfr-$MPFR_VERSION.tar.xz"
  (cd "mpfr-$MPFR_VERSION" &&
   ./configure --prefix="$PREFIX" --libdir="$PREFIX/lib" --with-gmp="$PREFIX" --disable-shared --enable-static CC="$CC" CFLAGS="-O3 $FMA_FLAGS" > configure.log &&
   make -j"$JOBS" > make.log && make install > install.log)
fi

## libieeep1788: header only, but p1788/version.hpp is generated by its CMake
if [ -f "$PREFIX/include/p1788/p1788.hpp" ]; then
  echo "== libieeep1788: already in $PREFIX"
else
  echo "== libieeep1788 $P1788_COMMIT"
  if [ ! -d libieeep1788 ]; then
    git clone -q https://github.com/nehmeier/libieeep1788.git libieeep1788
  fi
  git -C libieeep1788 checkout -q "$P1788_COMMIT"
  mkdir -p "$PREFIX/include"
  (cd libieeep1788 && find p1788 -name '*.hpp' | cpio -pdm --quiet "$PREFIX/include")
  sed -e 's/@P1788_VERSION_MAJOR@/0/g' -e 's/@P1788_VERSION_MINOR@/1/g' \
      -e 's/@P1788_VERSION_PATCH@/5/g' \
      libieeep1788/p1788/version.hpp.in > "$PREFIX/include/p1788/version.hpp"
fi

## filib++: the one FILIB_DIR gives, or IBEX's archive, built with its configure,
## in C++11: its dynamic exception specifications are errors in C++17, which
## GCC 11 and Clang 16 compile by default
if [ -n "$FILIB_DIR_GIVEN" ]; then
  [ -f "$FILIB_DIR_GIVEN/include/interval/interval.hpp" ] && [ -f "$FILIB_DIR_GIVEN/lib/libprim.a" ] \
    || die "no filib++ in $FILIB_DIR_GIVEN (include/interval/interval.hpp, lib/libprim.a)"
  echo "== filib++: $FILIB_DIR_GIVEN"
  echo "$FILIB_DIR_GIVEN" > "$WORK/filib-dir"
elif [ -f "$FILIB_DIR/include/interval/interval.hpp" ]; then
  echo "== filib++: already in $FILIB_DIR"
else
  echo "== filib++ $FILIB_VERSION"
  fetch "$FILIB_URL" "filibsrc-$FILIB_VERSION.tar.gz" "$FILIB_SHA256"
  rm -rf "filibsrc-$FILIB_VERSION" && tar xzf "filibsrc-$FILIB_VERSION.tar.gz"
  (cd "filibsrc-$FILIB_VERSION" &&
   ./configure --prefix="$PREFIX" --libdir="$PREFIX/lib" --disable-shared CXX="$CXX" CC="$CC" \
               CXXFLAGS="-std=c++11 -O3 $FMA_FLAGS -frounding-math -Wno-deprecated" > configure.log &&
   make -j"$JOBS" > make.log && make install > install.log)
  echo "$PREFIX" > "$WORK/filib-dir"
fi

## PROFIL/BIAS: its own Configure asks for the configuration interactively;
## Host.cfg, which it writes, is written here for x86-64 Linux, its compilers
## (gcc in that configuration) replaced by $CC and $CXX, in C++11 (its
## `register` is an error in C++17), and its -O2 by -O3 $FMA_FLAGS
## -ffp-contract=off: with -mfma and the contraction Clang does by default, its
## outward roundings x*(1+eps) + eta became fused multiply-adds, whose subnormal
## addend eta cost about 43 ns each, and sqrt, exp and log took 90 ns rather
## than 6 to 16 (i7-1185G7, Clang 18). make install copies the headers and the
## libraries into the source tree
if [ -f "$PROFIL_DIR/include/Interval.h" ]; then
  echo "== PROFIL/BIAS: already in $PROFIL_DIR"
else
  echo "== PROFIL/BIAS $PROFIL_VERSION"
  if [ -n "$PROFIL_TGZ" ]; then
    cp "$PROFIL_TGZ" "Profil-$PROFIL_VERSION.tgz"
  fi
  fetch "$PROFIL_URL" "Profil-$PROFIL_VERSION.tgz" "$PROFIL_SHA256"
  rm -rf "Profil-$PROFIL_VERSION" && tar xzf "Profil-$PROFIL_VERSION.tgz"
  (cd "Profil-$PROFIL_VERSION" &&
   printf '# Written by doc/compare/code/setup.sh, as Configure would\nARCH\t= x86-64-Linux-compat-gcc\ninclude $(BASEDIR)/config/$(ARCH)/Host.cfg\nCC\t= %s\nCCPLUS\t= %s\nCFLAGS\t:= $(patsubst -O2,-O3 %s -ffp-contract=off,$(CFLAGS))\nCPLUSFLAGS\t= $(CFLAGS) -std=c++11\n' "$CC" "$CXX" "$FMA_FLAGS" > Host.cfg &&
   make all > make.log 2>&1 && make install > install.log 2>&1 && make check > check.log 2>&1 &&
   grep -q "FAILED : 0" check.log)
  mkdir -p "$PROFIL_DIR"
  cp -r "Profil-$PROFIL_VERSION/include" "Profil-$PROFIL_VERSION/lib" "$PROFIL_DIR/"
fi

## GAOL, from this repository
if [ -f "$PREFIX/include/gaol/gaol.h" ] && [ -z "${FORCE_GAOL:-}" ]; then
  echo "== GAOL: already in $PREFIX (FORCE_GAOL=1 to rebuild)"
else
  echo "== GAOL ($(git -C "$ROOT_DIR" describe --always --dirty 2>/dev/null || echo "?"))"
  cmake -S "$ROOT_DIR" -B "$WORK/gaol-build" -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" \
        -DGAOL_FMA="$([ -n "$FMA_FLAGS" ] && echo ON || echo OFF)" \
        -DGAOL_FIND_MATHLIB=OFF > "$WORK/gaol-configure.log"
  cmake --build "$WORK/gaol-build" -j"$JOBS" > "$WORK/gaol-build.log"
  cmake --install "$WORK/gaol-build" > "$WORK/gaol-install.log"
fi

## The last GAOL of Frédéric Goualard, which GAOL v5 continues, with mathlib,
## both built with their configure, as his README has it for Linux, and static,
## as GAOL v5's library. Its configure gives -O3 and the SSE flags to g++
## alone: the flags GAOL v5 is built with in Release are given instead. The
## rounding direction is not preserved, as in GAOL v5 (his configure preserves
## it by default). mathlib is compiled with -ffp-contract=off: its exact
## products split the doubles, which fused multiply-adds would break
if [ -f "$GAOL_GOUALARD_PREFIX/include/gaol/gaol.h" ]; then
  echo "== GAOL $GAOL_GOUALARD_VERSION of Frédéric Goualard: already in $GAOL_GOUALARD_PREFIX"
else
  echo "== mathlib $MATHLIB_VERSION"
  fetch "$MATHLIB_URL" "mathlib-$MATHLIB_VERSION.tar.gz" "$MATHLIB_SHA256"
  rm -rf "mathlib-$MATHLIB_VERSION" && tar xzf "mathlib-$MATHLIB_VERSION.tar.gz"
  (cd "mathlib-$MATHLIB_VERSION" &&
   ./configure --prefix="$GAOL_GOUALARD_PREFIX" --libdir="$GAOL_GOUALARD_PREFIX/lib" --disable-shared \
               CC="$CC" CFLAGS="-O3 $FMA_FLAGS -ffp-contract=off" > configure.log &&
   make -j"$JOBS" > make.log && make install > install.log)

  echo "== GAOL $GAOL_GOUALARD_VERSION of Frédéric Goualard (${GAOL_GOUALARD_COMMIT:0:7})"
  if [ ! -d gaol-goualard ]; then
    git clone -q "$GAOL_GOUALARD_REPO" gaol-goualard
  fi
  git -C gaol-goualard checkout -q "$GAOL_GOUALARD_COMMIT"
  (cd gaol-goualard &&
   ./configure --prefix="$GAOL_GOUALARD_PREFIX" --libdir="$GAOL_GOUALARD_PREFIX/lib" --disable-shared \
               --disable-preserve-rounding \
               --with-mathlib-include="$GAOL_GOUALARD_PREFIX/include" \
               --with-mathlib-lib="$GAOL_GOUALARD_PREFIX/lib" \
               CC="$CC" CXX="$CXX" CFLAGS="-O3 $FMA_FLAGS -ffp-contract=off" \
               CXXFLAGS="-O3 -DNDEBUG -std=c++11 $IA_CXXFLAGS -msse2 -msse3 $FMA_FLAGS -fvisibility-inlines-hidden -fvisibility=hidden -funroll-loops -fomit-frame-pointer" \
               > configure.log &&
   make -j"$JOBS" > make.log && make install > install.log)
fi

## Solaris Studio f90
echo "== Solaris Studio ($F90)"
command -v "$F90" >/dev/null || die "$F90 not found: add Solaris Studio's bin to PATH, or set F90"
mkdir -p "$WORK/f90check" && cd "$WORK/f90check"
printf 'program c\n  interval(8) :: x\n  x = [1d0, 2d0]\n  print *, sup(x + x)\nend program\n' > check.f90
"$F90" -xia check.f90 -o check >/dev/null
[ "$(./check | tr -d ' ')" = "4.0" ] || die "$F90 -xia does not compute intervals"
"$F90" -V 2>&1 | head -1

echo "== done: everything is under $PREFIX"
