/*-*-C++-*------------------------------------------------------------------
 * gaol -- NOT Just Another Interval Library
 *--------------------------------------------------------------------------
 * Tests of this fork of GAOL: the elementary functions.
 *
 * The bounds GAOL computes are compared with the doubles on each side of the
 * exact values, computed with 2000 bits of precision (elementary_values.h,
 * generated by elementary_values.py): at doubles, at intervals between them,
 * and at intervals whose images are known exactly (extrema, poles, domains).
 * They have to enclose the exact values, within a few doubles.
 *
 * Copyright (c) 2026 ENSTA, France
 *
 * Created 2026-09-20 by Jordan NININ
 *--------------------------------------------------------------------------
 * gaol is a software distributed WITHOUT ANY WARRANTY. Read the associated
 * COPYING file for information.
 *--------------------------------------------------------------------------*/

#include "gaol_tests.h"
#include "elementary_values.h"

#include <algorithm>
#include <cstdlib>

using namespace gaol;
using namespace gaol_tests;

namespace
{
  // The largest distance from the tightest bounds allowed, in doubles: one,
  // every function being the value of a correctly rounded library, mathlib or
  // CORE-MATH, moved one double outward. It was 8, twice the 4 the hyperbolic
  // functions reached, their values from the libm being moved three doubles
  // outward (issue #1)
  const int limit = 1;

  // atan2 is the value of mathlib moved one double outward. CRlibm has no
  // atan2: built with it, GAOL takes the one of the libm moved three doubles
  // outward, as for the hyperbolic functions, up to four from the tightest
#if GAOL_USING_CRLIBM
  const int atan2_limit = 4;
#else
  const int atan2_limit = 1;
#endif

  typedef interval (*Unary)(const interval&);

  enum class Variation { increasing, decreasing, even, periodic };

  struct Function
  {
    Unary f;
    Variation variation;
  };

  const std::map<std::string, Function>& unary_functions()
  {
    static const std::map<std::string, Function> functions = {
      { "exp", { [](const interval& x) { return exp(x); }, Variation::increasing } },
      { "log", { [](const interval& x) { return log(x); }, Variation::increasing } },
      { "sin", { [](const interval& x) { return sin(x); }, Variation::periodic } },
      { "cos", { [](const interval& x) { return cos(x); }, Variation::periodic } },
      { "tan", { [](const interval& x) { return tan(x); }, Variation::periodic } },
      { "asin", { [](const interval& x) { return asin(x); }, Variation::increasing } },
      { "acos", { [](const interval& x) { return acos(x); }, Variation::decreasing } },
      { "atan", { [](const interval& x) { return atan(x); }, Variation::increasing } },
      { "sinh", { [](const interval& x) { return sinh(x); }, Variation::increasing } },
      { "cosh", { [](const interval& x) { return cosh(x); }, Variation::even } },
      { "tanh", { [](const interval& x) { return tanh(x); }, Variation::increasing } },
      { "asinh", { [](const interval& x) { return asinh(x); }, Variation::increasing } },
      { "acosh", { [](const interval& x) { return acosh(x); }, Variation::increasing } },
      { "atanh", { [](const interval& x) { return atanh(x); }, Variation::increasing } },
      { "sqrt", { [](const interval& x) { return sqrt(x); }, Variation::increasing } },
    };
    return functions;
  }

  // The number of doubles above from up to to, from <= to (limit + 1 when
  // there are more than limit)
  int doubles_between(double from, double to)
  {
    int n = 0;
    for (double t = from; t < to && n <= limit; t = next_double(t)) {
      ++n;
    }
    return n;
  }

  // Checks that r encloses [below, above], with bounds no more than max_doubles
  // doubles away from them
  template<class Describe>
  void expect_close(const std::string& name, const interval& r, double below, double above, const Describe& describe,
                    int max_doubles = limit)
  {
    if (check(name + ": encloses", !r.is_empty() && r.left() <= below && r.right() >= above, describe)) {
      check_distance(name, std::max(doubles_between(r.left(), below), doubles_between(above, r.right())), max_doubles,
                     describe);
    }
  }

  const UnaryValue& value(const char *function, double x)
  {
    for (const UnaryValue& v : unary_values) {
      if (std::strcmp(v.function, function) == 0 && v.x == x) {
        return v;
      }
    }
    std::printf("No value of %s at %s in elementary_values.h\n", function, hex(x).c_str());
    std::exit(1);
  }

  // Checks that r encloses [below, above], with bounds no more than slack away
  // from them
  template<class Describe>
  void expect_within(const std::string& name, const std::string& slack_name, const interval& r, double below, double above,
                     double slack, const Describe& describe)
  {
    if (check(name + ": encloses", !r.is_empty() && r.left() <= below && r.right() >= above, describe)) {
      RoundingToNearest nearest;
      check(name + ": no more than " + slack_name + " from the exact value", below - r.left() <= slack && r.right() - above <= slack,
            describe);
    }
  }

  void at_doubles()
  {
    for (const UnaryValue& v : unary_values) {
      const std::string f = v.function, name = f + "([x])";
      const auto arguments = [&] { return f + "(" + hex(v.x) + ")"; };
      const interval r = evaluate(name, [&] { return unary_functions().at(f).f(interval(v.x)); }, arguments);
      const auto describe = [&] {
        return arguments() + " = " + hex(r) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
      };
      if (f == "log") {
        // CORE-MATH's log in the upward rounding, where GAOL takes it
        // (GAOL_CORE_MATH_LOG, see gaol/gaol_core_math.h): the tightest bounds;
        // mathlib's value moved one double outward otherwise
#if defined(GAOL_CORE_MATH_LOG) && GAOL_CORE_MATH_LOG
        expect_close(name, r, v.below, v.above, describe, 0);
#else
        expect_close(name, r, v.below, v.above, describe);
#endif
      } else if (f == "sin" || f == "cos" || f == "tan") {
        // mathlib's values at the argument, moved one double outward: within
        // one double of the tightest bounds, at every magnitude. Beyond 2^25,
        // or next to an extremum or a pole, where the division of the argument
        // by an enclosure of pi cannot tell whether an extremum is reached,
        // the signs of the derivative tell (issue #6): GAOL's bounds were
        // x^2 2^-103 + 2^-51 away, cos([2^60]) was [-1, 1], and the tangent of
        // the double below pi/2 [-oo, +oo]
        expect_close(name, r, v.below, v.above, describe, 1);
      } else {
        expect_close(name, r, v.below, v.above, describe);
      }
    }
    // The functions of two intervals: pow() and atan2()
    for (const BinaryValue& v : binary_values) {
      const std::string name = std::string(v.function) + "([a],[b])";
      const auto arguments = [&] { return std::string(v.function) + "(" + hex(v.a) + ", " + hex(v.b) + ")"; };
      if (std::strcmp(v.function, "atan2") == 0) {
        // The value of mathlib moved one double outward
        const interval angle = evaluate(name, [&] { return atan2(interval(v.a), interval(v.b)); }, arguments);
        expect_close(name, angle, v.below, v.above, [&] {
          return arguments() + " = " + hex(angle) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
        }, atan2_limit);
        continue;
      }
      const interval r = evaluate(name, [&] { return pow(interval(v.a), interval(v.b)); }, arguments);
      // The pow of mathlib, correctly rounded, moved one double outward
      expect_close(name, r, v.below, v.above, [&] {
        return arguments() + " = " + hex(r) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
      }, 1);
      // The same with the exponent as a double
      const interval rd = evaluate("pow([a],b)", [&] { return pow(interval(v.a), v.b); }, arguments);
      expect_close("pow([a],b)", rd, v.below, v.above, [&] {
        return arguments() + " = " + hex(rd) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
      }, 1);
    }
  }

  // pow over boxes [xl, xu] x [yl, yu] of bases above 0, in every position
  // about the base 1 and the exponent 0, where its monotonicity changes
  void pow_of_boxes()
  {
    for (const PowBox& b : pow_boxes) {
      const interval X(b.xl, b.xu), Y(b.yl, b.yu);
      const auto describe_box = [&] { return "pow(" + hex(X) + ", " + hex(Y) + ")"; };
      const interval r = evaluate("pow([x],[y]) over boxes", [&] { return pow(X, Y); }, describe_box);
      const auto describe = [&] {
        return describe_box() + " = " + hex(r) + ", the hull of the powers being within ["
          + hex(b.least_below) + ", " + hex(b.greatest_above) + "]";
      };
      if (check("pow([x],[y]) over boxes: encloses", !r.is_empty() && r.left() <= b.least_below
                && r.right() >= b.greatest_above, describe)) {
        // A bound that is 1 (a base 1 or an exponent 0 at its corner) has to be it
        const int distance = std::max((b.least_below == 1.0 && b.least_above == 1.0) ? 2*doubles_between(r.left(), 1.0)
                                      : doubles_between(r.left(), b.least_below),
                                      (b.greatest_below == 1.0 && b.greatest_above == 1.0) ? 2*doubles_between(1.0, r.right())
                                      : doubles_between(b.greatest_above, r.right()));
        check_distance("pow([x],[y]) over boxes", distance, 1, describe);
      }
    }
  }

  // sin, cos and tan over intervals next to their extrema and poles, of width
  // about pi and 2 pi, and of consecutive doubles up to the largest: the hull
  // of the values, within one double, -1 and 1 being exact (issue #6)
  void trigonometric_intervals()
  {
    for (const TrigInterval& t : trig_intervals) {
      const std::string f = t.function, name = f + "([a,b]) next to extrema and poles";
      const interval X(t.a, t.b);
      const auto arguments = [&] { return f + "(" + hex(X) + ")"; };
      const interval r = evaluate(name, [&] { return unary_functions().at(f).f(X); }, arguments);
      const auto describe = [&] {
        return arguments() + " = " + hex(r) + ", the hull of the values being within ["
          + hex(t.least_below) + ", " + hex(t.greatest_above) + "]";
      };
      if (check(name + ": encloses", !r.is_empty() && r.left() <= t.least_below && r.right() >= t.greatest_above, describe)) {
        check_distance(name, std::max(doubles_between(r.left(), t.least_below), doubles_between(t.greatest_above, r.right())),
                       1, describe);
      }
    }
  }

  // atan2 of IEEE 1788-2015 over boxes [yl, yu] x [xl, xu] in every position
  // about the axes and the half-line y = 0, x < 0, where the angle jumps from
  // pi to -pi, and at the boxes whose hull is known: those with infinite
  // bounds, and those reduced to a piece of an axis
  void atan2_of_boxes()
  {
    for (const Atan2Box& b : atan2_boxes) {
      const interval Y(b.yl, b.yu), X(b.xl, b.xu);
      const auto describe_box = [&] { return "atan2(" + hex(Y) + ", " + hex(X) + ")"; };
      const interval r = evaluate("atan2([y],[x]) over boxes", [&] { return atan2(Y, X); }, describe_box);
      const auto describe = [&] {
        return describe_box() + " = " + hex(r) + ", the hull of the angles being within ["
          + hex(b.least_below) + ", " + hex(b.greatest_above) + "]";
      };
      if (check("atan2([y],[x]) over boxes: encloses", !r.is_empty() && r.left() <= b.least_below
                && r.right() >= b.greatest_above, describe)) {
        // A bound that is a double (0) has to be it
        const int distance = std::max((b.least_below == b.least_above) ? 2*doubles_between(r.left(), b.least_below)
                                      : doubles_between(r.left(), b.least_below),
                                      (b.greatest_below == b.greatest_above) ? 2*doubles_between(b.greatest_above, r.right())
                                      : doubles_between(b.greatest_above, r.right()));
        check_distance("atan2([y],[x]) over boxes", distance, atan2_limit, describe);
      }
    }

    const interval pi = interval::pi(), half_pi = interval::half_pi();
    const double oo = gaol_tests::inf;
    const struct { const char *name; interval Y, X; double l, r; } known[] = {
      { "atan2([0],[0])", interval(0.0), interval(0.0), 1.0, -1.0 },
      { "atan2([empty],[1])", interval::emptyset(), interval(1.0), 1.0, -1.0 },
      { "atan2([1],[empty])", interval(1.0), interval::emptyset(), 1.0, -1.0 },
      { "atan2([0],[1,2])", interval(0.0), interval(1.0, 2.0), 0.0, 0.0 },
      { "atan2([0],[-2,-1])", interval(0.0), interval(-2.0, -1.0), pi.left(), pi.right() },
      { "atan2([0],[-2,0])", interval(0.0), interval(-2.0, 0.0), pi.left(), pi.right() },
      { "atan2([0],[0,2])", interval(0.0), interval(0.0, 2.0), 0.0, 0.0 },
      { "atan2([0],[-1,1])", interval(0.0), interval(-1.0, 1.0), 0.0, pi.right() },
      { "atan2([1,2],[0])", interval(1.0, 2.0), interval(0.0), half_pi.left(), half_pi.right() },
      { "atan2([0,2],[0])", interval(0.0, 2.0), interval(0.0), half_pi.left(), half_pi.right() },
      { "atan2([-2,-1],[0])", interval(-2.0, -1.0), interval(0.0), -half_pi.right(), -half_pi.left() },
      { "atan2([-2,0],[0])", interval(-2.0, 0.0), interval(0.0), -half_pi.right(), -half_pi.left() },
      { "atan2([-1,1],[0])", interval(-1.0, 1.0), interval(0.0), -half_pi.right(), half_pi.right() },
      { "atan2([-1,0],[-2,-1])", interval(-1.0, 0.0), interval(-2.0, -1.0), -pi.right(), pi.right() },
      { "atan2([-1,1],[-2,-1])", interval(-1.0, 1.0), interval(-2.0, -1.0), -pi.right(), pi.right() },
      { "atan2([-1,0],[1,2]): at most 0", interval(-1.0, 0.0), interval(1.0, 2.0), -half_pi.right()*0.5, 0.0 },
      { "atan2([-oo,+oo],[-oo,+oo])", interval::universe(), interval::universe(), -pi.right(), pi.right() },
      { "atan2([1,+oo],[1,+oo])", interval(1.0, oo), interval(1.0, oo), 0.0, half_pi.right() },
      { "atan2([1,+oo],[-oo,-1])", interval(1.0, oo), interval(-oo, -1.0), half_pi.left(), pi.right() },
      { "atan2([-oo,-1],[-oo,-1])", interval(-oo, -1.0), interval(-oo, -1.0), -pi.right(), -half_pi.left() },
      { "atan2([-oo,-1],[1,+oo])", interval(-oo, -1.0), interval(1.0, oo), -half_pi.right(), 0.0 },
      { "atan2([-oo,+oo],[1,2])", interval::universe(), interval(1.0, 2.0), -half_pi.right(), half_pi.right() },
      { "atan2([1,2],[-oo,+oo])", interval(1.0, 2.0), interval::universe(), 0.0, pi.right() },
      { "atan2([1],[1]): pi/4", interval(1.0), interval(1.0), half_pi.left()*0.5, half_pi.right()*0.5 },
      { "atan2([-3],[3]): -pi/4", interval(-3.0), interval(3.0), -half_pi.right()*0.5, -half_pi.left()*0.5 },
    };
    for (const auto& k : known) {
      const interval r = evaluate(k.name, [&] { return atan2(k.Y, k.X); }, [&] { return std::string(k.name); });
      const bool ok = (k.l > k.r) ? r.is_empty() : (!r.is_empty() && r.left() == k.l && r.right() == k.r);
      check(std::string(k.name) + ": the tightest bounds", ok, [&] { return hex(r); });
    }
  }

  // At the intervals between two successive arguments of the table
  void at_intervals()
  {
    const std::size_t n = sizeof(unary_values)/sizeof(unary_values[0]);
    for (std::size_t i = 0; i + 1 < n; ++i) {
      const UnaryValue& u = unary_values[i];
      const UnaryValue& v = unary_values[i+1];
      if (std::strcmp(u.function, v.function) != 0 || !(u.x < v.x)) {
        continue;
      }
      const Function& f = unary_functions().at(u.function);
      const interval X(u.x, v.x);
      const std::string name = std::string(u.function) + "([x]) for intervals";
      const auto arguments = [&] { return std::string(u.function) + "(" + hex(X) + ")"; };
      const interval r = evaluate(name, [&] { return f.f(X); }, arguments);
      const auto describe = [&] { return arguments() + " = " + hex(r); };
      Variation variation = f.variation;
      if (variation == Variation::even) {
        variation = (u.x >= 0.0) ? Variation::increasing : ((v.x <= 0.0) ? Variation::decreasing : Variation::even);
      }
      switch (variation) {
        case Variation::increasing:
          expect_close(name, r, u.below, v.above, describe);
          break;
        case Variation::decreasing:
          expect_close(name, r, v.below, u.above, describe);
          break;
        case Variation::even: // cosh, whose minimum is cosh(0) = 1
          expect_close(name, r, 1.0, std::max(u.above, v.above), describe);
          break;
        case Variation::periodic: // The image contains the images of the bounds
          check(name + ": encloses", !r.is_empty() && r.left() <= std::min(u.below, v.below)
                                     && r.right() >= std::max(u.above, v.above), describe);
          break;
      }
    }
  }

  // At intervals whose images are known exactly
  void at_known_intervals()
  {
    const double pi_below = 0x1.921fb54442d18p+1, pi_above = 0x1.921fb54442d19p+1;

    struct Known
    {
      const char *name;
      interval (*f)();
      double below, above;
    };
    const Known known[] = {
      { "sin([1,2]), which contains pi/2", [] { return sin(interval(1., 2.)); }, value("sin", 1.).below, 1. },
      { "sin([4,5]), which contains 3pi/2", [] { return sin(interval(4., 5.)); }, -1., value("sin", 4.).above },
      { "sin([0,7]), wider than a period", [] { return sin(interval(0., 7.)); }, -1., 1. },
      { "cos([3,4]), which contains pi", [] { return cos(interval(3., 4.)); }, -1., value("cos", 4.).above },
      { "cos([-1,1]), which contains 0", [] { return cos(interval(-1., 1.)); }, value("cos", 1.).below, 1. },
      { "cos([0,7]), wider than a period", [] { return cos(interval(0., 7.)); }, -1., 1. },
      // sin(x) and cos(x) of a small x: GAOL computed sin(x) as cos(x - [pi/2]),
      // 4.4e-16 wide
      { "sin([1e-10])", [] { return sin(interval(1e-10)); }, previous_double(1e-10), 1e-10 },
      { "sin([-1e-300, 1e-300])", [] { return sin(interval(-1e-300, 1e-300)); }, -1e-300, 1e-300 },
      { "cos([1e-10])", [] { return cos(interval(1e-10)); }, previous_double(1.), 1. },
      { "tan([1,2]), which contains pi/2", [] { return tan(interval(1., 2.)); }, -inf, inf },
      { "tan([-1,1])", [] { return tan(interval(-1., 1.)); }, value("tan", -1.).below, value("tan", 1.).above },
      { "log([-1,1])", [] { return log(interval(-1., 1.)); }, -inf, 0. },
      { "log([0,1])", [] { return log(interval(0., 1.)); }, -inf, 0. },
      { "exp([-inf,0])", [] { return exp(interval(-inf, 0.)); }, 0., 1. },
      { "sqrt([-4,4])", [] { return sqrt(interval(-4., 4.)); }, 0., 2. },
      { "tanh([-inf,inf])", [] { return tanh(interval::universe()); }, -1., 1. },
      { "atanh([-1,1])", [] { return atanh(interval(-1., 1.)); }, -inf, inf },
      { "cosh([-inf,inf])", [] { return cosh(interval::universe()); }, 1., inf },
    };
    for (const Known& k : known) {
      const interval r = evaluate(k.name, k.f, [] { return std::string(); });
      const bool trigonometric = std::strncmp(k.name, "sin(", 4) == 0 || std::strncmp(k.name, "cos(", 4) == 0;
      expect_close(k.name, r, k.below, k.above, [&] { return hex(r); }, trigonometric ? 1 : limit);
    }

    // The functions where their value is a double, pi, pi/2 or pi/4, sinh and
    // cosh beyond the largest double, and tanh where it is closer to 1 than
    // the double below 1: the tightest bounds, which the values of the
    // mathematical library moved outward did not give
    const double max_double = std::numeric_limits<double>::max(), below_one = 0x1.fffffffffffffp-1;
    const Known exact[] = {
      { "sin([0])", [] { return sin(interval(0.)); }, 0., 0. },
      { "sin([-0,0])", [] { return sin(interval(-0., 0.)); }, 0., 0. },
      { "cos([0])", [] { return cos(interval(0.)); }, 1., 1. },
      { "tan([0])", [] { return tan(interval(0.)); }, 0., 0. },
      { "asin([0])", [] { return asin(interval(0.)); }, 0., 0. },
      { "asin([1])", [] { return asin(interval(1.)); }, pi_below/2, pi_above/2 },
      { "asin([-1])", [] { return asin(interval(-1.)); }, -pi_above/2, -pi_below/2 },
      { "asin([-2,2])", [] { return asin(interval(-2., 2.)); }, -pi_above/2, pi_above/2 },
      { "acos([1])", [] { return acos(interval(1.)); }, 0., 0. },
      { "acos([1,3])", [] { return acos(interval(1., 3.)); }, 0., 0. },
      { "acos([0])", [] { return acos(interval(0.)); }, pi_below/2, pi_above/2 },
      { "acos([-1])", [] { return acos(interval(-1.)); }, pi_below, pi_above },
      { "acos([-3,-1])", [] { return acos(interval(-3., -1.)); }, pi_below, pi_above },
      { "acos([-2,2])", [] { return acos(interval(-2., 2.)); }, 0., pi_above },
      { "atan([0])", [] { return atan(interval(0.)); }, 0., 0. },
      { "atan([1])", [] { return atan(interval(1.)); }, pi_below/4, pi_above/4 },
      { "atan([-1])", [] { return atan(interval(-1.)); }, -pi_above/4, -pi_below/4 },
      { "atan([-oo,+oo])", [] { return atan(interval::universe()); }, -pi_above/2, pi_above/2 },
      { "sinh([0])", [] { return sinh(interval(0.)); }, 0., 0. },
      { "sinh([711,+oo])", [] { return sinh(interval(711., inf)); }, max_double, inf },
      { "sinh([-oo,-MAX])", [] { return sinh(interval(-inf, -std::numeric_limits<double>::max())); }, -inf, -max_double },
      { "cosh([0])", [] { return cosh(interval(0.)); }, 1., 1. },
      { "cosh([MAX,+oo])", [] { return cosh(interval(std::numeric_limits<double>::max(), inf)); }, max_double, inf },
      { "cosh([-800,-711])", [] { return cosh(interval(-800., -711.)); }, max_double, inf },
      { "tanh([0])", [] { return tanh(interval(0.)); }, 0., 0. },
      { "tanh([MAX,+oo])", [] { return tanh(interval(std::numeric_limits<double>::max(), inf)); }, below_one, 1. },
      { "tanh([-30,-20])", [] { return tanh(interval(-30., -20.)); }, -1., -below_one },
      { "asinh([0])", [] { return asinh(interval(0.)); }, 0., 0. },
      { "acosh([1])", [] { return acosh(interval(1.)); }, 0., 0. },
      { "acosh([0,1])", [] { return acosh(interval(0., 1.)); }, 0., 0. },
      { "atanh([0])", [] { return atanh(interval(0.)); }, 0., 0. },
    };
    for (const Known& e : exact) {
      const interval r = evaluate(e.name, e.f, [] { return std::string(); });
      check(std::string(e.name) + ": the tightest bounds", r.left() == e.below && r.right() == e.above, [&] { return hex(r); });
    }

    struct Empty
    {
      const char *name;
      interval (*f)();
    };
    const Empty empty[] = {
      { "log([-2,-1])", [] { return log(interval(-2., -1.)); } },
      // log is defined on (0, +oo) (IEEE 1788-2015, Table 9.1): GAOL gave
      // [-oo,-MAX] for these two
      { "log([-4,0])", [] { return log(interval(-4., 0.)); } },
      { "log([0])", [] { return log(interval(0.)); } },
      { "sqrt([-4,-1])", [] { return sqrt(interval(-4., -1.)); } },
      { "asin([2,3])", [] { return asin(interval(2., 3.)); } },
      { "acos([-3,-2])", [] { return acos(interval(-3., -2.)); } },
      { "acosh([-1,0.5])", [] { return acosh(interval(-1., 0.5)); } },
      { "atanh([2,3])", [] { return atanh(interval(2., 3.)); } },
    };
    for (const Empty& e : empty) {
      bool threw = false;
      interval r;
      try {
        r = e.f();
      } catch (...) {
        threw = true;
      }
      check(std::string(e.name) + ": empty", !threw && r.is_empty(), [&] { return threw ? std::string("exception") : hex(r); });
    }
  }
}

namespace
{
  // pow() with a floating-point exponent, and with negative bases, after the
  // tests of Codac for the fix ported to GAOL
  // (tests/core/domains/interval/codac2_tests_Interval_operations.cpp)
  void powers()
  {
    struct Close
    {
      const char *name;
      interval (*f)();
      double below, above;
    };
    const Close close[] = {
      { "pow([4],0.5)", [] { return pow(interval(4.), 0.5); }, 2., 2. },
      { "pow([4],0.5f)", [] { return pow(interval(4.), 0.5f); }, 2., 2. },
      { "pow([4],1.5)", [] { return pow(interval(4.), 1.5); }, 8., 8. },
      { "pow([4,9],0.5)", [] { return pow(interval(4., 9.), 0.5); }, 2., 3. },
      { "pow([4],-0.5)", [] { return pow(interval(4.), -0.5); }, 0.5, 0.5 },
      { "pow([0,4],0.5)", [] { return pow(interval(0., 4.), 0.5); }, 0., 2. },
      { "pow([-4,9],0.5), whose negative part is out of the domain", [] { return pow(interval(-4., 9.), 0.5); }, 0., 3. },
      { "pow([-2,3],[1,2]), whose negative part is out of the domain", [] { return pow(interval(-2., 3.), interval(1., 2.)); }, 0., 9. },
      { "pow([-10,10],-2.0)", [] { return pow(interval(-10., 10.), -2.0); }, previous_double(0.01), inf },
    };
    for (const Close& c : close) {
      const interval r = evaluate(c.name, c.f, [] { return std::string(); });
      expect_close(c.name, r, c.below, c.above, [&] { return hex(r); });
    }

    struct Equal
    {
      const char *name;
      interval (*f)();
      double lo, hi;
    };
    const Equal equal[] = {
      { "pow([-2,3],3.0), with a negative base and an integer exponent", [] { return pow(interval(-2., 3.), 3.0); }, -8., 27. },
      { "pow([-2],2.0)", [] { return pow(interval(-2.), 2.0); }, 4., 4. },
      { "pow([2,3],4.0)", [] { return pow(interval(2., 3.), 4.0); }, 16., 81. },
      { "pow([4],0.0)", [] { return pow(interval(4.), 0.0); }, 1., 1. },
      { "pow([-2,3],[3]), with a negative base and an integer exponent", [] { return pow(interval(-2., 3.), interval(3.)); }, -8., 27. },
      { "pow([-2,3],[2])", [] { return pow(interval(-2., 3.), interval(2.)); }, 0., 9. },
    };
    for (const Equal& e : equal) {
      const interval r = evaluate(e.name, e.f, [] { return std::string(); });
      check(std::string(e.name) + ": exact", r.left() == e.lo && r.right() == e.hi, [&] { return hex(r); });
    }

    const interval x(2., 3.);
    const interval with_double = pow(x, 1.5), with_interval = pow(x, interval(1.5));
    check("pow([2,3],1.5) = pow([2,3],[1.5])", with_double.left() == with_interval.left() && with_double.right() == with_interval.right(),
          [&] { return hex(with_double) + " and " + hex(with_interval); });

    struct Empty
    {
      const char *name;
      interval (*f)();
    };
    const Empty empty[] = {
      { "pow([-4,-1],0.5)", [] { return pow(interval(-4., -1.), 0.5); } },
      { "pow([-4,-1],[0.5])", [] { return pow(interval(-4., -1.), interval(0.5)); } },
      { "pow([4],+oo)", [] { return pow(interval(4.), inf); } },
      { "pow([4],-oo)", [] { return pow(interval(4.), -inf); } },
      { "pow([4],NaN)", [] { return pow(interval(4.), std::numeric_limits<double>::quiet_NaN()); } },
      { "pow(empty,1.5)", [] { return pow(interval::emptyset(), 1.5); } },
      { "pow([4],empty)", [] { return pow(interval(4.), interval::emptyset()); } },
    };
    for (const Empty& e : empty) {
      const interval r = evaluate(e.name, e.f, [] { return std::string(); });
      check(std::string(e.name) + ": empty", r.is_empty(), [&] { return hex(r); });
    }

    // An integer exponent beyond the ints, for which pow(const interval&, int)
    // cannot be called, still takes the integer power rather than the real
    // one, and gives [-oo,+oo] whatever the base
    const Empty universe[] = {
      { "pow([-2,-1],[1e10])", [] { return pow(interval(-2., -1.), interval(1e10)); } },
      { "pow([-1,-0.5],[2^32+1])", [] { return pow(interval(-1., -0.5), interval(4294967297.0)); } },
      { "pow([2,3],[2^31]), with a positive base", [] { return pow(interval(2., 3.), interval(2147483648.0)); } },
      { "pow([0.25,0.5],[-2^31-1]), with a positive base", [] { return pow(interval(0.25, 0.5), interval(-2147483649.0)); } },
      { "pow([-2,3],1e10)", [] { return pow(interval(-2., 3.), 1e10); } },
      { "pow([2,3],2^31)", [] { return pow(interval(2., 3.), 2147483648.0); } },
    };
    for (const Empty& u : universe) {
      const interval r = evaluate(u.name, u.f, [] { return std::string(); });
      check(std::string(u.name) + ": [-oo,+oo]", r.left() == -inf && r.right() == inf, [&] { return hex(r); });
    }
    const interval beyond_empty = pow(interval::emptyset(), interval(1e10));
    check("pow(empty,[1e10]): empty", beyond_empty.is_empty(), [&] { return hex(beyond_empty); });

    // The bounds of the ints still take the integer power
    const interval largest = pow(interval(-1.), interval(2147483647.0)), smallest = pow(interval(-1.), interval(-2147483648.0));
    check("pow([-1],[2^31-1]) and pow([-1],[-2^31]), at the bounds of the ints: exact",
          largest.left() == -1. && largest.right() == -1. && smallest.left() == 1. && smallest.right() == 1.,
          [&] { return hex(largest) + " and " + hex(smallest); });

    // Special cases of IEEE 1788-2015 (Table 9.1, footnotes b and c): pown(x,0)
    // is 1 for any x, 0 included, and pown(0,p) has no value for p < 0; pow(0,y)
    // is 0 for y > 0, and has no value for y <= 0; [+oo] and [-oo] contain no
    // real number (10.5.8)
    const Equal special[] = {
      // exp(0) = 1 and log(1) = 0 exactly, which the bounds of the
      // mathematical library moved outward did not give
      { "exp([0])", [] { return exp(interval(0.)); }, 1., 1. },
      { "exp([-oo,0])", [] { return exp(interval(-inf, 0.)); }, 0., 1. },
      { "log([1])", [] { return log(interval(1.)); }, 0., 0. },
      { "log([0,1])", [] { return log(interval(0., 1.)); }, -inf, 0. },
      { "log([1,+oo])", [] { return log(interval(1., inf)); }, 0., inf },
      { "pow([1],[-oo,+oo]), 1^y = 1", [] { return pow(interval(1.), interval::universe()); }, 1., 1. },
      { "pow([1],[2.5])", [] { return pow(interval(1.), interval(2.5)); }, 1., 1. },
      { "pow([0,1],[1,+oo])", [] { return pow(interval(0., 1.), interval(1., inf)); }, 0., 1. },
      { "pow([0],[0]), pown(0,0) = 1", [] { return pow(interval(0.), interval(0.)); }, 1., 1. },
      { "pow([0],0.0)", [] { return pow(interval(0.), 0.0); }, 1., 1. },
      { "pow([-oo,+oo],[0])", [] { return pow(interval::universe(), interval(0.)); }, 1., 1. },
      { "pow([0,2],[-1]), without x = 0", [] { return pow(interval(0., 2.), interval(-1.)); }, 0.5, inf },
      { "pow([-2,0],[-1]), without x = 0", [] { return pow(interval(-2., 0.), interval(-1.)); }, -inf, -0.5 },
      { "pow([0],[0.5]), pow(0,y) = 0 for y > 0", [] { return pow(interval(0.), interval(0.5)); }, 0., 0. },
      { "pow([0],0.5)", [] { return pow(interval(0.), 0.5); }, 0., 0. },
      { "pow([-2,0],[2.5])", [] { return pow(interval(-2., 0.), interval(2.5)); }, 0., 0. },
      { "pow([0],[0,1]), without y = 0", [] { return pow(interval(0.), interval(0., 1.)); }, 0., 0. },
      { "pow([0],[-1,1]), without y <= 0", [] { return pow(interval(0.), interval(-1., 1.)); }, 0., 0. },
    };
    for (const Equal& e : special) {
      const interval r = evaluate(e.name, e.f, [] { return std::string(); });
      check(std::string(e.name) + ": exact", r.left() == e.lo && r.right() == e.hi, [&] { return hex(r); });
    }
    const Empty no_value[] = {
      { "pow([0],[-1]), pown(0,p) for p < 0", [] { return pow(interval(0.), interval(-1.)); } },
      { "pow([0],[-0.5]), pow(0,y) for y < 0", [] { return pow(interval(0.), interval(-0.5)); } },
      { "pow([0],-0.5)", [] { return pow(interval(0.), -0.5); } },
      { "pow([-2,0],[-0.5])", [] { return pow(interval(-2., 0.), interval(-0.5)); } },
      { "pow([0],[-1,0]), pow(0,y) for y <= 0", [] { return pow(interval(0.), interval(-1., 0.)); } },
      { "pow([4],[+oo]), interval(+oo) being the empty set", [] { return pow(interval(4.), interval(inf)); } },
      { "pow([4],[-oo]), interval(-oo) being the empty set", [] { return pow(interval(4.), interval(-inf)); } },
    };
    for (const Empty& e : no_value) {
      const interval r = evaluate(e.name, e.f, [] { return std::string(); });
      check(std::string(e.name) + ": empty", r.is_empty(), [&] { return hex(r); });
    }
  }
}

int main()
{
  gaol::init();
  at_doubles();
  at_intervals();
  at_known_intervals();
  pow_of_boxes();
  atan2_of_boxes();
  trigonometric_intervals();
  powers();
  const int status = summary();
  gaol::cleanup();
  return status;
}
