/*-*-C++-*------------------------------------------------------------------
 * gaol -- NOT Just Another Interval Library
 *--------------------------------------------------------------------------
 * Tests of this fork of GAOL: the elementary functions.
 *
 * The bounds GAOL computes are compared with the doubles on each side of the
 * exact values, computed with 2000 bits of precision (elementary_values.h,
 * generated by elementary_values.py): at doubles, at intervals between them,
 * and at intervals whose images are known exactly (extrema, poles, domains).
 * They have to enclose the exact values, within a few doubles.
 *--------------------------------------------------------------------------
 * gaol is a software distributed WITHOUT ANY WARRANTY. Read the associated
 * COPYING file for information.
 *--------------------------------------------------------------------------*/

#include "gaol_tests.h"
#include "elementary_values.h"

#include <algorithm>
#include <cstdlib>

using namespace gaol;
using namespace gaol_tests;

namespace
{
  // The largest distance from the tightest bounds allowed
  const int limit = 1000;

  typedef interval (*Unary)(const interval&);

  enum class Variation { increasing, decreasing, even, periodic };

  struct Function
  {
    Unary f;
    Variation variation;
  };

  const std::map<std::string, Function>& unary_functions()
  {
    static const std::map<std::string, Function> functions = {
      { "exp", { [](const interval& x) { return exp(x); }, Variation::increasing } },
      { "log", { [](const interval& x) { return log(x); }, Variation::increasing } },
      { "sin", { [](const interval& x) { return sin(x); }, Variation::periodic } },
      { "cos", { [](const interval& x) { return cos(x); }, Variation::periodic } },
      { "tan", { [](const interval& x) { return tan(x); }, Variation::periodic } },
      { "asin", { [](const interval& x) { return asin(x); }, Variation::increasing } },
      { "acos", { [](const interval& x) { return acos(x); }, Variation::decreasing } },
      { "atan", { [](const interval& x) { return atan(x); }, Variation::increasing } },
      { "sinh", { [](const interval& x) { return sinh(x); }, Variation::increasing } },
      { "cosh", { [](const interval& x) { return cosh(x); }, Variation::even } },
      { "tanh", { [](const interval& x) { return tanh(x); }, Variation::increasing } },
      { "asinh", { [](const interval& x) { return asinh(x); }, Variation::increasing } },
      { "acosh", { [](const interval& x) { return acosh(x); }, Variation::increasing } },
      { "atanh", { [](const interval& x) { return atanh(x); }, Variation::increasing } },
      { "sqrt", { [](const interval& x) { return sqrt(x); }, Variation::increasing } },
    };
    return functions;
  }

  // The number of doubles above from up to to, from <= to (limit + 1 when
  // there are more than limit)
  int doubles_between(double from, double to)
  {
    int n = 0;
    for (double t = from; t < to && n <= limit; t = next_double(t)) {
      ++n;
    }
    return n;
  }

  // Checks that r encloses [below, above], with bounds no more than limit
  // doubles away from them
  template<class Describe>
  void expect_close(const std::string& name, const interval& r, double below, double above, const Describe& describe)
  {
    if (check(name + ": encloses", !r.is_empty() && r.left() <= below && r.right() >= above, describe)) {
      check_distance(name, std::max(doubles_between(r.left(), below), doubles_between(above, r.right())), limit, describe);
    }
  }

  const UnaryValue& value(const char *function, double x)
  {
    for (const UnaryValue& v : unary_values) {
      if (std::strcmp(v.function, function) == 0 && v.x == x) {
        return v;
      }
    }
    std::printf("No value of %s at %s in elementary_values.h\n", function, hex(x).c_str());
    std::exit(1);
  }

  // Checks that r encloses [below, above], with bounds no more than slack away
  // from them
  template<class Describe>
  void expect_within(const std::string& name, const std::string& slack_name, const interval& r, double below, double above,
                     double slack, const Describe& describe)
  {
    if (check(name + ": encloses", !r.is_empty() && r.left() <= below && r.right() >= above, describe)) {
      RoundingToNearest nearest;
      check(name + ": no more than " + slack_name + " from the exact value", below - r.left() <= slack && r.right() - above <= slack,
            describe);
    }
  }

  void at_doubles()
  {
    for (const UnaryValue& v : unary_values) {
      const std::string f = v.function, name = f + "([x])";
      const auto arguments = [&] { return f + "(" + hex(v.x) + ")"; };
      const interval r = evaluate(name, [&] { return unary_functions().at(f).f(interval(v.x)); }, arguments);
      const auto describe = [&] {
        return arguments() + " = " + hex(r) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
      };
      if (f == "sin" || f == "cos" || f == "tan") {
        // GAOL reduces the argument modulo an interval enclosing pi, whose
        // width, 2^-51, the bounds take on for each multiple of pi subtracted:
        // they are checked to within 2^-49 max(1,|x|), times the derivative
        // for tan, where that tells something (below 1)
        RoundingToNearest nearest;
        double slack = std::ldexp(std::max(1.0, std::fabs(v.x)), -49);
        if (f == "tan") {
          slack *= 1.0 + v.above*v.above;
        }
        if (slack < 1.0) {
          expect_within(name, "2^-49 max(1,|x|)", r, v.below, v.above, slack, describe);
        } else {
          check(name + ": encloses", !r.is_empty() && r.left() <= v.below && r.right() >= v.above, describe);
        }
      } else {
        expect_close(name, r, v.below, v.above, describe);
      }
    }
    // pow(), the only function of two intervals in the table: GAOL does not
    // implement atan2(), which raises unavailable_feature_error
    for (const BinaryValue& v : binary_values) {
      const std::string name = std::string(v.function) + "([a],[b])";
      const auto arguments = [&] { return std::string(v.function) + "(" + hex(v.a) + ", " + hex(v.b) + ")"; };
      const interval r = evaluate(name, [&] { return pow(interval(v.a), interval(v.b)); }, arguments);
      // pow(a,b) = exp(b log(a)): the relative width of log(a), a few 2^-52,
      // is multiplied by b log(a) in exp()
      RoundingToNearest nearest;
      const double relative = std::ldexp(std::max(1.0, std::fabs(v.b*std::log(v.a))), -49);
      expect_within(name, "2^-49 max(1,|b log(a)|) relatively", r, v.below, v.above,
                    relative*std::max(std::fabs(v.below), std::fabs(v.above)), [&] {
        return arguments() + " = " + hex(r) + ", exact value between " + hex(v.below) + " and " + hex(v.above);
      });
    }
  }

  // At the intervals between two successive arguments of the table
  void at_intervals()
  {
    const std::size_t n = sizeof(unary_values)/sizeof(unary_values[0]);
    for (std::size_t i = 0; i + 1 < n; ++i) {
      const UnaryValue& u = unary_values[i];
      const UnaryValue& v = unary_values[i+1];
      if (std::strcmp(u.function, v.function) != 0 || !(u.x < v.x)) {
        continue;
      }
      const Function& f = unary_functions().at(u.function);
      const interval X(u.x, v.x);
      const std::string name = std::string(u.function) + "([x]) for intervals";
      const auto arguments = [&] { return std::string(u.function) + "(" + hex(X) + ")"; };
      const interval r = evaluate(name, [&] { return f.f(X); }, arguments);
      const auto describe = [&] { return arguments() + " = " + hex(r); };
      Variation variation = f.variation;
      if (variation == Variation::even) {
        variation = (u.x >= 0.0) ? Variation::increasing : ((v.x <= 0.0) ? Variation::decreasing : Variation::even);
      }
      switch (variation) {
        case Variation::increasing:
          expect_close(name, r, u.below, v.above, describe);
          break;
        case Variation::decreasing:
          expect_close(name, r, v.below, u.above, describe);
          break;
        case Variation::even: // cosh, whose minimum is cosh(0) = 1
          expect_close(name, r, 1.0, std::max(u.above, v.above), describe);
          break;
        case Variation::periodic: // The image contains the images of the bounds
          check(name + ": encloses", !r.is_empty() && r.left() <= std::min(u.below, v.below)
                                     && r.right() >= std::max(u.above, v.above), describe);
          break;
      }
    }
  }

  // At intervals whose images are known exactly
  void at_known_intervals()
  {
    const double pi_below = 0x1.921fb54442d18p+1, pi_above = 0x1.921fb54442d19p+1;
    const double half_pi_above = pi_above/2.0;

    struct Known
    {
      const char *name;
      interval (*f)();
      double below, above;
    };
    const Known known[] = {
      { "sin([1,2]), which contains pi/2", [] { return sin(interval(1., 2.)); }, value("sin", 1.).below, 1. },
      { "sin([4,5]), which contains 3pi/2", [] { return sin(interval(4., 5.)); }, -1., value("sin", 4.).above },
      { "sin([0,7]), wider than a period", [] { return sin(interval(0., 7.)); }, -1., 1. },
      { "cos([3,4]), which contains pi", [] { return cos(interval(3., 4.)); }, -1., value("cos", 4.).above },
      { "cos([-1,1]), which contains 0", [] { return cos(interval(-1., 1.)); }, value("cos", 1.).below, 1. },
      { "cos([0,7]), wider than a period", [] { return cos(interval(0., 7.)); }, -1., 1. },
      { "tan([1,2]), which contains pi/2", [] { return tan(interval(1., 2.)); }, -inf, inf },
      { "tan([-1,1])", [] { return tan(interval(-1., 1.)); }, value("tan", -1.).below, value("tan", 1.).above },
      { "log([-1,1])", [] { return log(interval(-1., 1.)); }, -inf, 0. },
      { "log([0,1])", [] { return log(interval(0., 1.)); }, -inf, 0. },
      { "exp([-inf,0])", [] { return exp(interval(-inf, 0.)); }, 0., 1. },
      { "sqrt([-4,4])", [] { return sqrt(interval(-4., 4.)); }, 0., 2. },
      { "asin([-2,2])", [] { return asin(interval(-2., 2.)); }, -half_pi_above, half_pi_above },
      { "acos([-2,2])", [] { return acos(interval(-2., 2.)); }, 0., pi_above },
      { "acos([1,3])", [] { return acos(interval(1., 3.)); }, 0., 0. },
      { "acos([-3,-1])", [] { return acos(interval(-3., -1.)); }, pi_below, pi_above },
      { "atan([-inf,inf])", [] { return atan(interval::universe()); }, -half_pi_above, half_pi_above },
      { "tanh([-inf,inf])", [] { return tanh(interval::universe()); }, -1., 1. },
      { "acosh([0,1])", [] { return acosh(interval(0., 1.)); }, 0., 0. },
      { "atanh([-1,1])", [] { return atanh(interval(-1., 1.)); }, -inf, inf },
      { "cosh([-inf,inf])", [] { return cosh(interval::universe()); }, 1., inf },
    };
    for (const Known& k : known) {
      const interval r = evaluate(k.name, k.f, [] { return std::string(); });
      expect_close(k.name, r, k.below, k.above, [&] { return hex(r); });
    }

    struct Empty
    {
      const char *name;
      interval (*f)();
    };
    const Empty empty[] = {
      { "log([-2,-1])", [] { return log(interval(-2., -1.)); } },
      { "sqrt([-4,-1])", [] { return sqrt(interval(-4., -1.)); } },
      { "asin([2,3])", [] { return asin(interval(2., 3.)); } },
      { "acos([-3,-2])", [] { return acos(interval(-3., -2.)); } },
      { "acosh([-1,0.5])", [] { return acosh(interval(-1., 0.5)); } },
      { "atanh([2,3])", [] { return atanh(interval(2., 3.)); } },
    };
    for (const Empty& e : empty) {
      bool threw = false;
      interval r;
      try {
        r = e.f();
      } catch (...) {
        threw = true;
      }
      check(std::string(e.name) + ": empty", !threw && r.is_empty(), [&] { return threw ? std::string("exception") : hex(r); });
    }
  }
}

int main()
{
  gaol::init();
  at_doubles();
  at_intervals();
  at_known_intervals();
  const int status = summary();
  gaol::cleanup();
  return status;
}
