// Generated by tests/extended_precision_values.py, which says what it is: do not edit
//
// Copyright (c) 2026 ENSTA, France
//
// Created 2026-09-21 by Jordan NININ

struct ExtendedPrecisionValue { const char *function; double a, b, below, above, nearest; };

const ExtendedPrecisionValue nearest_values[] = {
  {"exp", -0x1.74910d52d3051p+9, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0000000000001p-1022},
  {"exp", -0x1.74910d52d304fp+9, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0000000000001p-1022},
  {"exp2", -0x1.0cbffffffffffp+10, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0000000000001p-1022},
  {"exp2", -0x1.0cbfffffffffcp+10, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0000000000001p-1022},
  {"exp10", -0x1.0024f40ea956dp+5, 0x0.0p+0, 0x1.8e7ab9e9ec72ep-107, 0x1.8e7ab9e9ec72fp-107, 0x1.8e7ab9e9ec72fp-107},
  {"exp10", -0x1.9676a8f8f7257p-1, 0x0.0p+0, 0x1.4932700aa22c1p-3, 0x1.4932700aa22c2p-3, 0x1.4932700aa22c1p-3},
  {"exp2m1", 0x1.0de65d6192ee7p+0, 0x0.0p+0, 0x1.13a2f16c996f2p+0, 0x1.13a2f16c996f3p+0, 0x1.13a2f16c996f3p+0},
  {"log2", 0x1.ff14ac6b1df1ep+1013, 0x0.0p+0, 0x1.faffab0c312b2p+9, 0x1.faffab0c312b3p+9, 0x1.faffab0c312b3p+9},
  {"log10", 0x1.4f5b4118dbe1bp+0, 0x0.0p+0, 0x1.e0530fd594474p-4, 0x1.e0530fd594475p-4, 0x1.e0530fd594475p-4},
  {"cos", -0x1.c5edf099902e4p+4, 0x0.0p+0, -0x1.fda14086499fap-1, -0x1.fda14086499f9p-1, -0x1.fda14086499f9p-1},
  {"tan", -0x1.deadd0f15d335p+187, 0x0.0p+0, -0x1.91a7d9118c079p-2, -0x1.91a7d9118c078p-2, -0x1.91a7d9118c079p-2},
  {"atan", 0x1.b1aff86528049p+0, 0x0.0p+0, 0x1.099cd64960f3ap+0, 0x1.099cd64960f3bp+0, 0x1.099cd64960f3bp+0},
  {"sinh", 0x1.966ce0e262bc8p+0, 0x0.0p+0, 0x1.2c013069bd70bp+1, 0x1.2c013069bd70cp+1, 0x1.2c013069bd70bp+1},
  {"sinh", -0x1.8fd856caa732cp-2, 0x0.0p+0, -0x1.9a156204b1fc0p-2, -0x1.9a156204b1fbfp-2, -0x1.9a156204b1fbfp-2},
  {"cosh", 0x1.3a234bdf3eb05p-1, 0x0.0p+0, 0x1.31b72d7c81f96p+0, 0x1.31b72d7c81f97p+0, 0x1.31b72d7c81f97p+0},
  {"cosh", -0x1.74a2a194b738ep-3, 0x0.0p+0, 0x1.043fd11db93f1p+0, 0x1.043fd11db93f2p+0, 0x1.043fd11db93f1p+0},
  {"tanh", 0x1.30fc1931f09c9p+4, 0x0.0p+0, 0x1.fffffffffffffp-1, 0x1.0000000000000p+0, 0x1.fffffffffffffp-1},
  {"tanh", 0x1.30fc1931f09c6p+4, 0x0.0p+0, 0x1.fffffffffffffp-1, 0x1.0000000000000p+0, 0x1.fffffffffffffp-1},
  {"asinh", 0x1.279dfc4ce17bcp+7, 0x0.0p+0, 0x1.6c19d4abdae91p+2, 0x1.6c19d4abdae92p+2, 0x1.6c19d4abdae91p+2},
  {"acosh", 0x1.05b07f909b43bp+937, 0x0.0p+0, 0x1.4518d62f51edcp+9, 0x1.4518d62f51eddp+9, 0x1.4518d62f51eddp+9},
  {"acosh", 0x1.2792401729230p+10, 0x0.0p+0, 0x1.f12cab73aee73p+2, 0x1.f12cab73aee74p+2, 0x1.f12cab73aee73p+2},
  {"cbrt", -0x1.03826f09eeb07p+3, 0x0.0p+0, -0x1.012a1ea68238fp+1, -0x1.012a1ea68238ep+1, -0x1.012a1ea68238fp+1},
  {"cbrt", -0x1.3bdc651e51463p+10, 0x0.0p+0, -0x1.59f0e05471ee7p+3, -0x1.59f0e05471ee6p+3, -0x1.59f0e05471ee7p+3},
  {"sinpi", -0x1.559b8c0370720p-443, 0x0.0p+0, -0x1.0c4c48cab5bb8p-441, -0x1.0c4c48cab5bb7p-441, -0x1.0c4c48cab5bb7p-441},
  {"sinpi", -0x1.7e13629b39a0ep+3, 0x0.0p+0, 0x1.8099fe4d1440dp-3, 0x1.8099fe4d1440ep-3, 0x1.8099fe4d1440dp-3},
  {"cospi", 0x1.46ab83f903022p+8, 0x0.0p+0, -0x1.049adf1c577b5p-1, -0x1.049adf1c577b4p-1, -0x1.049adf1c577b5p-1},
  {"cospi", 0x1.17d3b45cf70dap-1, 0x0.0p+0, -0x1.2a5a601584a78p-3, -0x1.2a5a601584a77p-3, -0x1.2a5a601584a77p-3},
  {"tanpi", 0x1.5deecb6973603p-658, 0x0.0p+0, 0x1.12d6298eaec3cp-656, 0x1.12d6298eaec3dp-656, 0x1.12d6298eaec3dp-656},
  {"tanpi", 0x1.2356cc2b555fcp-3, 0x0.0p+0, 0x1.eabff4621a33dp-2, 0x1.eabff4621a33ep-2, 0x1.eabff4621a33dp-2},
};

const ExtendedPrecisionValue directed_values[] = {
  {"exp2", -0x1.0cc0000000000p+10, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"exp2", -0x1.f400000000000p+10, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"exp2", -0x1.fffffffffffffp+1023, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"exp10", -0x1.747d4d25cd55fp+339, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"exp10", -0x1.9000000000000p+8, 0x0.0p+0, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"exp10", 0x1.34413509f79ffp+8, 0x0.0p+0, 0x1.fffffffffffffp+1023, gaol_tests::inf, gaol_tests::inf},
  {"exp10", 0x1.fffffffffffffp+1023, 0x0.0p+0, 0x1.fffffffffffffp+1023, gaol_tests::inf, gaol_tests::inf},
  {"expm1", -0x1.62e42fefa39efp+9, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"expm1", -0x1.9000000000000p+9, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"exp2m1", -0x1.0000000000000p+10, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"exp2m1", -0x1.1300000000000p+10, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"exp10m1", -0x1.34413509f79ffp+8, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"exp10m1", -0x1.9000000000000p+8, 0x0.0p+0, -0x1.0000000000000p+0, -0x1.fffffffffffffp-1, -0x1.0000000000000p+0},
  {"cosh", 0x1.633ce8fb9f87ep+9, 0x0.0p+0, 0x1.fffffffffffffp+1023, gaol_tests::inf, gaol_tests::inf},
  {"cosh", 0x1.fffffffffffffp+1023, 0x0.0p+0, 0x1.fffffffffffffp+1023, gaol_tests::inf, gaol_tests::inf},
  {"cosh", -0x1.fffffffffffffp+1023, 0x0.0p+0, 0x1.fffffffffffffp+1023, gaol_tests::inf, gaol_tests::inf},
  {"cospi", 0x0.0000000000001p-1022, 0x0.0p+0, 0x1.fffffffffffffp-1, 0x1.0000000000000p+0, 0x1.0000000000000p+0},
  {"cospi", -0x0.0000000000002p-1022, 0x0.0p+0, 0x1.fffffffffffffp-1, 0x1.0000000000000p+0, 0x1.0000000000000p+0},
  {"atan2", 0x1.56e1fc2f8f359p-997, 0x1.7e43c8800759cp+996, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"atan2", 0x1.415ac65b4ab1dp-767, 0x1.dfb75d0ec2aadp+747, 0x0.0p+0, 0x0.0000000000001p-1022, 0x0.0p+0},
  {"atan2", -0x1.592f3da6af564p-793, 0x1.03a828d452c31p+434, -0x0.0000000000001p-1022, -0x0.0p+0, -0x0.0p+0},
};

