/* <stdint.h> before the code of flex, which defines INT8_MIN and the other
   limits of integer types where <stdint.h> has not defined them: the
   <stdint.h> of Visual C++, which the prologue includes after that code,
   redefined them (warning C4005). */
#include <stdint.h>

#line 8 "lex.gaol_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer gaol__create_buffer
#define yy_delete_buffer gaol__delete_buffer
#define yy_scan_buffer gaol__scan_buffer
#define yy_scan_string gaol__scan_string
#define yy_scan_bytes gaol__scan_bytes
#define yy_init_buffer gaol__init_buffer
#define yy_flush_buffer gaol__flush_buffer
#define yy_load_buffer_state gaol__load_buffer_state
#define yy_switch_to_buffer gaol__switch_to_buffer
#define yypush_buffer_state gaol_push_buffer_state
#define yypop_buffer_state gaol_pop_buffer_state
#define yyensure_buffer_stack gaol_ensure_buffer_stack
#define yy_flex_debug gaol__flex_debug
#define yyin gaol_in
#define yyleng gaol_leng
#define yylex gaol_lex
#define yylineno gaol_lineno
#define yyout gaol_out
#define yyrestart gaol_restart
#define yytext gaol_text
#define yywrap gaol_wrap
#define yyalloc gaol_alloc
#define yyrealloc gaol_realloc
#define yyfree gaol_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define gaol__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer gaol__create_buffer
#endif

#ifdef yy_delete_buffer
#define gaol__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer gaol__delete_buffer
#endif

#ifdef yy_scan_buffer
#define gaol__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer gaol__scan_buffer
#endif

#ifdef yy_scan_string
#define gaol__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string gaol__scan_string
#endif

#ifdef yy_scan_bytes
#define gaol__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes gaol__scan_bytes
#endif

#ifdef yy_init_buffer
#define gaol__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer gaol__init_buffer
#endif

#ifdef yy_flush_buffer
#define gaol__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer gaol__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define gaol__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state gaol__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define gaol__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer gaol__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define gaol_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state gaol_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define gaol_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state gaol_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define gaol_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack gaol_ensure_buffer_stack
#endif

#ifdef yylex
#define gaol_lex_ALREADY_DEFINED
#else
#define yylex gaol_lex
#endif

#ifdef yyrestart
#define gaol_restart_ALREADY_DEFINED
#else
#define yyrestart gaol_restart
#endif

#ifdef yylex_init
#define gaol_lex_init_ALREADY_DEFINED
#else
#define yylex_init gaol_lex_init
#endif

#ifdef yylex_init_extra
#define gaol_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra gaol_lex_init_extra
#endif

#ifdef yylex_destroy
#define gaol_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy gaol_lex_destroy
#endif

#ifdef yyget_debug
#define gaol_get_debug_ALREADY_DEFINED
#else
#define yyget_debug gaol_get_debug
#endif

#ifdef yyset_debug
#define gaol_set_debug_ALREADY_DEFINED
#else
#define yyset_debug gaol_set_debug
#endif

#ifdef yyget_extra
#define gaol_get_extra_ALREADY_DEFINED
#else
#define yyget_extra gaol_get_extra
#endif

#ifdef yyset_extra
#define gaol_set_extra_ALREADY_DEFINED
#else
#define yyset_extra gaol_set_extra
#endif

#ifdef yyget_in
#define gaol_get_in_ALREADY_DEFINED
#else
#define yyget_in gaol_get_in
#endif

#ifdef yyset_in
#define gaol_set_in_ALREADY_DEFINED
#else
#define yyset_in gaol_set_in
#endif

#ifdef yyget_out
#define gaol_get_out_ALREADY_DEFINED
#else
#define yyget_out gaol_get_out
#endif

#ifdef yyset_out
#define gaol_set_out_ALREADY_DEFINED
#else
#define yyset_out gaol_set_out
#endif

#ifdef yyget_leng
#define gaol_get_leng_ALREADY_DEFINED
#else
#define yyget_leng gaol_get_leng
#endif

#ifdef yyget_text
#define gaol_get_text_ALREADY_DEFINED
#else
#define yyget_text gaol_get_text
#endif

#ifdef yyget_lineno
#define gaol_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno gaol_get_lineno
#endif

#ifdef yyset_lineno
#define gaol_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno gaol_set_lineno
#endif

#ifdef yywrap
#define gaol_wrap_ALREADY_DEFINED
#else
#define yywrap gaol_wrap
#endif

#ifdef yyalloc
#define gaol_alloc_ALREADY_DEFINED
#else
#define yyalloc gaol_alloc
#endif

#ifdef yyrealloc
#define gaol_realloc_ALREADY_DEFINED
#else
#define yyrealloc gaol_realloc
#endif

#ifdef yyfree
#define gaol_free_ALREADY_DEFINED
#else
#define yyfree gaol_free
#endif

#ifdef yytext
#define gaol_text_ALREADY_DEFINED
#else
#define yytext gaol_text
#endif

#ifdef yyleng
#define gaol_leng_ALREADY_DEFINED
#else
#define yyleng gaol_leng
#endif

#ifdef yyin
#define gaol_in_ALREADY_DEFINED
#else
#define yyin gaol_in
#endif

#ifdef yyout
#define gaol_out_ALREADY_DEFINED
#else
#define yyout gaol_out
#endif

#ifdef yy_flex_debug
#define gaol__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug gaol__flex_debug
#endif

#ifdef yylineno
#define gaol_lineno_ALREADY_DEFINED
#else
#define yylineno gaol_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[128] =
    {   0,
        0,    0,   46,   44,   43,   45,   30,   31,   35,   33,
       32,   34,   44,   36,   37,   37,   28,   29,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   26,   27,
       43,    0,    0,   39,   40,   37,   42,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,    0,    0,   39,    0,
       42,   42,   42,    0,    0,   38,    0,    0,    0,    0,
        0,   13,    0,    0,    0,    0,    8,    3,    9,    0,
       10,   14,    0,   15,    0,   39,    0,    0,   40,    0,
       42,    0,    0,    0,   20,   21,   22,   17,    7,    6,

        0,    0,    0,    0,   18,   12,   19,    0,   39,    0,
       41,   23,   24,   16,   25,    1,    0,    0,    0,    2,
        0,    0,    0,    0,    4,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
       13,   13,   13,   13,   13,   13,   13,    1,    1,   15,
        1,   16,   17,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,    1,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,    1,   37,   38,   39,    1,
       40,    1,   41,    1,   42,    1,   43,   19,   44,   45,

       46,   47,   48,   49,   50,    1,    1,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   36,    1,   60,   61,
       62,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    3,    3,    3,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[130] =
    {   0,
        0,    0,  153,  379,  141,  379,  379,  379,  379,   53,
      379,   58,   61,  379,   66,   72,  379,  379,   57,   39,
       53,   68,   58,   60,   60,   72,   81,   81,  379,  379,
      131,   96,  122,  128,  134,  145,  151,  169,  107,   95,
      102,  126,   96,  159,  129,  131,  139,  148,  151,  154,
      379,   63,  157,  155,  160,  194,  202,  211,  214,  225,
      228,  208,  171,  249,  233,  253,    0,  238,  164,  204,
      206,  226,  100,  223,  220,  242,  379,  244,  379,   61,
      379,  246,  237,  252,  268,  271,  290,  274,  277,  293,
      296,  267,  269,  304,  287,  289,  301,  379,  379,  379,

      280,  287,  292,  290,  379,  379,  379,  315,  318,  321,
      327,  379,  379,  379,  379,  379,  303,  311,  313,  379,
      311,  318,  312,  317,  379,  379,  379,  375,   61
    } ;

static const flex_int16_t yy_def[130] =
    {   0,
      127,    1,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  128,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  129,  128,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  129,  129,  127,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,    0,  127,  127
    } ;

static const flex_int16_t yy_nxt[442] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   16,   17,   18,    4,   19,    4,   20,
       21,   22,    4,    4,    4,   23,   24,    4,   25,    4,
       26,    4,    4,   27,   28,    4,    4,    4,    4,   29,
       30,    4,   19,   20,   21,   22,    4,    4,    4,   23,
       24,    4,   25,    4,   26,    4,    4,   27,   28,    4,
        4,    4,   32,   92,   33,   33,   33,   32,   43,   33,
       33,   33,   34,   34,   34,   35,   40,   36,   36,   36,
       44,   35,   37,   36,   36,   36,   48,   38,   37,   49,
       41,   42,   43,   38,   50,   45,   46,   51,   55,   81,

       40,   52,  104,   39,   44,   47,   53,   56,   56,   56,
       48,   38,   54,   49,   41,   42,   67,   38,   50,   45,
       46,   51,   81,   55,   69,   52,   39,   70,   47,   72,
       53,   57,   31,   33,   33,   33,   54,   99,   37,   34,
       34,   34,   31,   71,   37,   59,   59,   59,   69,   58,
       37,   70,  127,   72,   35,   60,   36,   36,   36,   75,
       99,   37,   61,   61,   61,   76,   38,   62,   71,   77,
       78,   63,   64,   58,   79,   65,   73,   65,   80,   60,
       66,   66,   66,   75,   74,   82,   63,   83,   84,   76,
       38,  127,   64,   77,   78,   63,   64,   95,   79,  127,

      127,   73,   80,  127,  127,   56,   56,   56,   74,   82,
       37,   83,   84,   56,   56,   56,   64,   85,   37,   85,
      127,   95,   86,   86,   86,   59,   59,   59,   63,   64,
       37,   88,   96,   88,   97,   87,   89,   89,   89,   61,
       61,   61,  127,   63,   66,   66,   66,   93,   63,   64,
       98,  100,   63,   64,  101,   90,   96,   90,   97,   87,
       91,   91,   91,   63,   66,   66,   66,  102,   94,  103,
      105,  106,   63,   64,   98,  100,  107,  127,  101,   86,
       86,   86,   86,   86,   86,   89,   89,   89,   89,   89,
       89,  102,   94,  103,  105,  106,  108,   94,  108,   94,

      107,  109,  109,  109,   91,   91,   91,   91,   91,   91,
      110,  112,  110,  113,  114,  111,  111,  111,  116,  117,
      118,   94,  119,   94,  120,  115,  109,  109,  109,  109,
      109,  109,  111,  111,  111,  112,  121,  113,  111,  111,
      111,  116,  122,  117,  118,  123,  119,  124,  120,  115,
      125,  126,  127,  127,  127,  127,  127,  127,  127,  127,
      121,  127,  127,  127,  127,  127,  122,  127,  127,  123,
      127,  124,  127,  125,  127,  126,   68,   68,    3,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127
    } ;

static const flex_int16_t yy_chk[442] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   10,  129,   10,   10,   10,   12,   20,   12,
       12,   12,   13,   13,   13,   15,   19,   15,   15,   15,
       21,   16,   15,   16,   16,   16,   23,   15,   16,   24,
       19,   19,   20,   16,   25,   22,   22,   26,   28,   52,

       19,   26,   80,   15,   21,   22,   27,   32,   32,   32,
       23,   15,   27,   24,   19,   19,   39,   16,   25,   22,
       22,   26,   52,   28,   40,   26,   15,   41,   22,   43,
       27,   33,   31,   33,   33,   33,   27,   73,   33,   34,
       34,   34,    5,   42,   34,   35,   35,   35,   40,   34,
       35,   41,    3,   43,   36,   35,   36,   36,   36,   45,
       73,   36,   37,   37,   37,   46,   36,   37,   42,   47,
       48,   37,   37,   34,   49,   38,   44,   38,   50,   35,
       38,   38,   38,   45,   44,   53,   37,   54,   55,   46,
       36,    0,   63,   47,   48,   37,   37,   69,   49,    0,

        0,   44,   50,    0,    0,   56,   56,   56,   44,   53,
       56,   54,   55,   57,   57,   57,   63,   58,   57,   58,
        0,   69,   58,   58,   58,   59,   59,   59,   62,   62,
       59,   60,   70,   60,   71,   59,   60,   60,   60,   61,
       61,   61,    0,   62,   65,   65,   65,   68,   61,   61,
       72,   74,   62,   62,   75,   64,   70,   64,   71,   59,
       64,   64,   64,   61,   66,   66,   66,   76,   68,   78,
       82,   83,   61,   61,   72,   74,   84,    0,   75,   85,
       85,   85,   86,   86,   86,   88,   88,   88,   89,   89,
       89,   76,   68,   78,   82,   83,   87,   92,   87,   93,

       84,   87,   87,   87,   90,   90,   90,   91,   91,   91,
       94,   95,   94,   96,   97,   94,   94,   94,  101,  102,
      103,   92,  104,   93,  117,   97,  108,  108,  108,  109,
      109,  109,  110,  110,  110,   95,  118,   96,  111,  111,
      111,  101,  119,  102,  103,  121,  104,  122,  117,   97,
      123,  124,    0,    0,    0,    0,    0,    0,    0,    0,
      118,    0,    0,    0,    0,    0,  119,    0,    0,  121,
        0,  122,    0,  123,    0,  124,  128,  128,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gaol_interval_lexer.lpp"
#line 2 "gaol_interval_lexer.lpp"
/*-*-C++-*------------------------------------------------------------------
 * gaol -- NOT Just Another Interval Library
 *--------------------------------------------------------------------------
 * This file is part of the gaol distribution. Gaol was primarily
 * developed at the Swiss Federal Institute of Technology, Lausanne,
 * Switzerland, and is now developed at the Laboratoire d'Informatique de
 * Nantes-Atlantique, France.
 *
 * Copyright (c) 2001 Swiss Federal Institute of Technology, Switzerland
 * Copyright (c) 2002-2006 Laboratoire d'Informatique de
 *                         Nantes-Atlantique, France
 *--------------------------------------------------------------------------
 * gaol is a software distributed WITHOUT ANY WARRANTY. Read the associated
 * COPYING file for information.
 *--------------------------------------------------------------------------
 * CVS: $Id: gaol_interval_lexer.lpp 191 2012-03-06 17:08:58Z goualard $
 * Last modified:
 * By:
 *--------------------------------------------------------------------------*/

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cstddef>
#include <limits>
#include <string>
#include <vector>
#include <stdint.h>
#include "gaol/gaol_config.h"
#include "gaol/gaol_interval.h"
#include "gaol/gaol_expression.h"
#include "gaol/gaol_exceptions.h"


/*
  The following 'namespace' statement must appear before including
  gaol/gaol_interval_parser.h
 */
using namespace gaol;

#include "gaol/gaol_interval_parser.h"
#include "gaol/gaol_exact.h"
#include "gaol/gaol_fpu.h"

#define YY_NEVER_INTERACTIVE 1


extern int gaol_error(char *s ...);

/*
  Numbers are read exactly, whatever the C library. A number no double is
  exactly is represented by the tightest interval of doubles enclosing it.
  GAOL read it with strtod() rounding downward then upward, and told it from a
  double by the inexact flag strtod() raised; it read integers rounded to
  nearest. Not every C library rounds strtod() in the rounding direction and
  raises the flag: the C runtime of Windows, with Visual C++ or MinGW, and musl
  on 64-bit ARM processors round to nearest whatever the direction and raise no
  flag, so that "0.1" was read as the double nearest to 1/10, which does not
  enclose it. strtod() now gives a double near the number, which the number is
  compared with exactly, as integers, to find the doubles on each side of it.
*/
namespace {

  // A natural number, as digits in base 2^32, least significant first, with no
  // leading zero digit (0 has no digit)
  typedef std::vector<uint32_t> gaol_natural;

  // n = n*m + a, with m > 0
  void gaol_natural_mul_add(gaol_natural& n, uint32_t m, uint32_t a)
  {
    uint64_t carry = a;
    for (std::size_t i = 0; i < n.size(); ++i) {
      const uint64_t t = static_cast<uint64_t>(n[i])*m + carry;
      n[i] = static_cast<uint32_t>(t);
      carry = t >> 32;
    }
    if (carry != 0) {
      n.push_back(static_cast<uint32_t>(carry));
    }
  }

  // n = n*5^e, with e >= 0
  void gaol_natural_mul_pow5(gaol_natural& n, long e)
  {
    for (; e >= 13; e -= 13) {
      gaol_natural_mul_add(n, 1220703125u, 0); // 5^13
    }
    uint32_t m = 1;
    for (; e > 0; --e) {
      m *= 5;
    }
    gaol_natural_mul_add(n, m, 0);
  }

  // n = n*2^e, with e >= 0
  void gaol_natural_shift_left(gaol_natural& n, long e)
  {
    if (n.empty()) {
      return;
    }
    const unsigned int bits = static_cast<unsigned int>(e % 32);
    if (bits != 0) {
      uint32_t carry = 0;
      for (std::size_t i = 0; i < n.size(); ++i) {
        const uint32_t d = n[i];
        n[i] = (d << bits) | carry;
        carry = d >> (32 - bits);
      }
      if (carry != 0) {
        n.push_back(carry);
      }
    }
    n.insert(n.begin(), static_cast<std::size_t>(e / 32), 0u);
  }

  // The sign of a - b
  int gaol_natural_compare(const gaol_natural& a, const gaol_natural& b)
  {
    if (a.size() != b.size()) {
      return (a.size() < b.size()) ? -1 : 1;
    }
    for (std::size_t i = a.size(); i-- > 0; ) {
      if (a[i] != b[i]) {
        return (a[i] < b[i]) ? -1 : 1;
      }
    }
    return 0;
  }

  // The sign of v - x, v being the number s writes, as the rules below match
  // numbers (decimal digits with an optional point and exponent, or, after
  // 0x, hexadecimal digits with an optional point and a binary exponent), and
  // x a double
  int gaol_compare_number(const char *s, double x)
  {
    // v = N*10^k*2^k2, N being written with ndigits digits
    gaol_natural N;
    long k = 0, k2 = 0, ndigits = 0;
    const bool hexadecimal = (s[0] == '0' && (s[1] == 'x' || s[1] == 'X'));
    const uint32_t base = hexadecimal ? 16 : 10;
    if (hexadecimal) {
      s += 2;
    }
    bool fraction = false;
    for (; *s != '\0' && (hexadecimal ? (*s != 'p' && *s != 'P') : (*s != 'e' && *s != 'E')); ++s) {
      if (*s == '.') {
        fraction = true;
        continue;
      }
      const uint32_t digit = static_cast<uint32_t>((*s >= '0' && *s <= '9') ? *s - '0'
                                                   : ((*s | 0x20) - 'a' + 10));
      if (ndigits != 0 || digit != 0) {
        gaol_natural_mul_add(N, base, digit);
        ++ndigits;
      }
      if (fraction) {
        if (hexadecimal) {
          k2 -= 4;
        } else {
          --k;
        }
      }
    }
    if (*s != '\0') { // Exponent
      ++s;
      const bool negative = (*s == '-');
      if (*s == '-' || *s == '+') {
        ++s;
      }
      long e = 0;
      for (; *s != '\0'; ++s) {
        if (e < 100000) { // Far beyond the doubles already
          e = 10*e + (*s - '0');
        }
      }
      (hexadecimal ? k2 : k) += negative ? -e : e;
    }

    if (N.empty()) { // v = 0
      return (x < 0.0) ? 1 : ((x > 0.0) ? -1 : 0);
    }
    if (!(x > 0.0)) {
      return 1;
    }
    if (x > std::numeric_limits<double>::max()) {
      return -1;
    }
    // 10^(k+ndigits-1) <= v < 10^(k+ndigits), respectively
    // 2^(k2+4(ndigits-1)) <= v < 2^(k2+4 ndigits), far above the largest
    // double or below the least positive one
    if (hexadecimal ? k2 + 4*(ndigits - 1) > 1025 : k + ndigits - 1 > 310) {
      return 1;
    }
    if (hexadecimal ? k2 + 4*ndigits < -1080 : k + ndigits < -330) {
      return -1;
    }

    // x = M*2^e, M being an integer of 53 bits
    int ex;
    const double f = std::frexp(x, &ex);
    const uint64_t M = static_cast<uint64_t>(std::ldexp(f, 53));
    const long e = static_cast<long>(ex) - 53;

    // N*5^k*2^(k+k2) compared with M*2^e
    gaol_natural A(N), B;
    B.push_back(static_cast<uint32_t>(M));
    B.push_back(static_cast<uint32_t>(M >> 32));
    if (k >= 0) {
      gaol_natural_mul_pow5(A, k);
    } else {
      gaol_natural_mul_pow5(B, -k);
    }
    const long kb = k + k2;
    if (kb >= e) {
      gaol_natural_shift_left(A, kb - e);
    } else {
      gaol_natural_shift_left(B, e - kb);
    }
    return gaol_natural_compare(A, B);
  }

  // The tightest interval of doubles [l, r] enclosing the number s, with no
  // sign; returns whether s is a double, l and r being it
  bool gaol_enclose_number(const char *s, double& l, double& r)
  {
    GAOL_RND_PRESERVE();
    round_nearest();
    double lo = strtod(s,NULL);
    // lo is moved to the greatest double below the number
    int sign = gaol_compare_number(s, lo);
    while (sign < 0) {
      lo = previous_float(lo);
      sign = gaol_compare_number(s, lo);
    }
    for (;;) {
      const double hi = next_float(lo);
      const int sign_hi = gaol_compare_number(s, hi);
      if (sign_hi < 0) {
        GAOL_RND_RESTORE();
        l = lo;
        r = (sign == 0) ? lo : hi;
        return sign == 0;
      }
      lo = hi;
      sign = sign_hi;
    }
  }

  // Reads the number s: returns NUMBER, with gaol_lval.d set to it, if it is a
  // double, and INTERVAL_CST, with gaol_lval.itv set to the tightest interval
  // of doubles enclosing it, otherwise
  int gaol_read_number(const char *s)
  {
    double l, r;
    if (gaol_enclose_number(s, l, r)) {
      gaol_lval.d = l;
      return NUMBER;
    }
    (gaol_lval.itv).l = l;
    (gaol_lval.itv).r = r;
    return INTERVAL_CST;
  }

  // Natural numbers written in decimal, most significant digit first
  std::string gaol_decimal_strip(const std::string& a)
  {
    const std::size_t i = a.find_first_not_of('0');
    return (i == std::string::npos) ? std::string("0") : a.substr(i);
  }

  // The sign of a - b
  int gaol_decimal_compare(const std::string& a, const std::string& b)
  {
    const std::string sa = gaol_decimal_strip(a), sb = gaol_decimal_strip(b);
    if (sa.size() != sb.size()) {
      return (sa.size() < sb.size()) ? -1 : 1;
    }
    return (sa < sb) ? -1 : ((sa > sb) ? 1 : 0);
  }

  // a + b, or a - b with a >= b
  std::string gaol_decimal_add_sub(const std::string& a, const std::string& b, bool subtract)
  {
    std::string res;
    int carry = 0;
    for (std::size_t i = 0; i < a.size() || i < b.size() || carry != 0; ++i) {
      const int da = (i < a.size()) ? a[a.size() - 1 - i] - '0' : 0;
      const int db = (i < b.size()) ? b[b.size() - 1 - i] - '0' : 0;
      int d = subtract ? da - db - carry : da + db + carry;
      carry = 0;
      if (d < 0) {
        d += 10;
        carry = 1;
      } else if (d > 9) {
        d -= 10;
        carry = 1;
      }
      res.insert(res.begin(), static_cast<char>('0' + d));
    }
    return gaol_decimal_strip(res);
  }

  // A signed decimal integer: its sign and its magnitude
  struct gaol_decimal
  {
    bool negative;
    std::string magnitude;
  };

  // a + b, for signed decimal integers
  gaol_decimal gaol_decimal_add(const gaol_decimal& a, const gaol_decimal& b)
  {
    gaol_decimal res;
    if (a.negative == b.negative) {
      res.negative = a.negative;
      res.magnitude = gaol_decimal_add_sub(a.magnitude, b.magnitude, false);
    } else if (gaol_decimal_compare(a.magnitude, b.magnitude) >= 0) {
      res.negative = a.negative;
      res.magnitude = gaol_decimal_add_sub(a.magnitude, b.magnitude, true);
    } else {
      res.negative = b.negative;
      res.magnitude = gaol_decimal_add_sub(b.magnitude, a.magnitude, true);
    }
    return res;
  }

  // The tightest interval of doubles [l, r] enclosing a*10^q
  void gaol_enclose_decimal(const gaol_decimal& a, long q, double& l, double& r)
  {
    const std::string s = a.magnitude + "e" + std::to_string(q);
    double lo, hi;
    gaol_enclose_number(s.c_str(), lo, hi);
    if (a.negative) {
      l = -hi;
      r = -lo;
    } else {
      l = lo;
      r = hi;
    }
  }

  /*
    Reads a number in the uncertain form of IEEE 1788-2015 (9.7.4, 12.11.3,
    fork of GAOL): m?rve, m being a decimal number with an optional sign, r a
    natural number of units of the last place of m (half a unit when absent)
    or ?, for an infinite radius, v the direction d or u, and e an exponent
    written as e and an integer. Returns UNCERTAIN_CST, with gaol_lval.itv set
    to the tightest interval of doubles enclosing the interval the number
    denotes: [m-r, m+r] times 10^e, [m-r, m] for d, [m, m+r] for u.
  */
  int gaol_read_uncertain(const char *s)
  {
    gaol_decimal m;
    m.negative = (*s == '-');
    if (*s == '-' || *s == '+') {
      ++s;
    }
    long places = 0; // Digits after the point
    bool fraction = false;
    for (; *s != '?'; ++s) {
      if (*s == '.') {
        fraction = true;
        continue;
      }
      m.magnitude += *s;
      if (fraction) {
        ++places;
      }
    }
    ++s; // '?'
    bool infinite = false;
    std::string radius;
    if (*s == '?') {
      infinite = true;
      ++s;
    } else {
      for (; *s >= '0' && *s <= '9'; ++s) {
        radius += *s;
      }
    }
    char direction = 0;
    if (*s == 'd' || *s == 'D' || *s == 'u' || *s == 'U') {
      direction = static_cast<char>(*s | 0x20);
      ++s;
    }
    long exponent = 0;
    if (*s == 'e' || *s == 'E') {
      ++s;
      const bool negative = (*s == '-');
      if (*s == '-' || *s == '+') {
        ++s;
      }
      for (; *s != '\0'; ++s) {
        if (exponent < 100000) { // Far beyond the doubles already
          exponent = 10*exponent + (*s - '0');
        }
      }
      if (negative) {
        exponent = -exponent;
      }
    }
    m.magnitude = gaol_decimal_strip(m.magnitude);

    double l, r;
    if (infinite) {
      // m??d is [-oo, m], m??u is [m, +oo], m?? is [-oo, +oo]
      double ml, mr;
      gaol_enclose_decimal(m, exponent - places, ml, mr);
      l = (direction == 'u') ? ml : -GAOL_INFINITY;
      r = (direction == 'd') ? mr : GAOL_INFINITY;
    } else {
      // With one more decimal place, m and the radius are integers: 10m and
      // 10r, or 5 for half a unit
      gaol_decimal m10 = m, r10, minus_r10;
      m10.magnitude += "0";
      r10.negative = false;
      r10.magnitude = radius.empty() ? std::string("5") : radius + "0";
      minus_r10.negative = true;
      minus_r10.magnitude = r10.magnitude;
      const long q = exponent - places - 1;
      double lo, hi;
      gaol_enclose_decimal((direction == 'u') ? m10 : gaol_decimal_add(m10, minus_r10), q, l, hi);
      gaol_enclose_decimal((direction == 'd') ? m10 : gaol_decimal_add(m10, r10), q, lo, r);
    }
    (gaol_lval.itv).l = l;
    (gaol_lval.itv).r = r;
    return UNCERTAIN_CST;
  }

}

namespace gaol {
  // The sign of v - x, v being the number s writes, with no sign, and x a
  // double, compared exactly: for the output of intervals (gaol_interval.cpp),
  // whose decimal bounds are rounded outward whatever the C library
  int compare_number_with_double(const char *s, double x)
  {
    return gaol_compare_number(s, x);
  }
}
#line 1287 "lex.gaol_.c"

/* yyunput() and yyinput() are not used. The case of letters is ignored, as
   IEEE 1788-2015 has it for literals (9.7.1): [Empty], [1, Inf] and 1E3 are
   read (fork of GAOL) */
#define YY_NO_INPUT 1
#line 1293 "lex.gaol_.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 464 "gaol_interval_lexer.lpp"


#line 1511 "lex.gaol_.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 128 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 379 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 466 "gaol_interval_lexer.lpp"
{ return EMPTY_STR; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 467 "gaol_interval_lexer.lpp"
{ return ENTIRE_STR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 468 "gaol_interval_lexer.lpp"
{ return INFINITY_STR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 469 "gaol_interval_lexer.lpp"
{ return INFINITY_STR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 470 "gaol_interval_lexer.lpp"
{ return PI_STR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 471 "gaol_interval_lexer.lpp"
{ return DMIN_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 472 "gaol_interval_lexer.lpp"
{ return DMAX_STR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 473 "gaol_interval_lexer.lpp"
{ return EXP_STR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 474 "gaol_interval_lexer.lpp"
{ return LOG_STR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 475 "gaol_interval_lexer.lpp"
{ return POW_STR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 476 "gaol_interval_lexer.lpp"
{ return NTH_ROOT_STR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 477 "gaol_interval_lexer.lpp"
{ return SQRT_STR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 478 "gaol_interval_lexer.lpp"
{ return COS_STR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 479 "gaol_interval_lexer.lpp"
{ return SIN_STR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 480 "gaol_interval_lexer.lpp"
{ return TAN_STR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 481 "gaol_interval_lexer.lpp"
{ return ATAN2_STR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 482 "gaol_interval_lexer.lpp"
{ return COSH_STR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 483 "gaol_interval_lexer.lpp"
{ return SINH_STR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 484 "gaol_interval_lexer.lpp"
{ return TANH_STR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 485 "gaol_interval_lexer.lpp"
{ return ACOS_STR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 486 "gaol_interval_lexer.lpp"
{ return ASIN_STR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 487 "gaol_interval_lexer.lpp"
{ return ATAN_STR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 488 "gaol_interval_lexer.lpp"
{ return ACOSH_STR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 489 "gaol_interval_lexer.lpp"
{ return ASINH_STR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 490 "gaol_interval_lexer.lpp"
{ return ATANH_STR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 491 "gaol_interval_lexer.lpp"
{ return '['; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 492 "gaol_interval_lexer.lpp"
{ return ']'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 493 "gaol_interval_lexer.lpp"
{ return '<'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 494 "gaol_interval_lexer.lpp"
{ return '>'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 495 "gaol_interval_lexer.lpp"
{ return '('; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 496 "gaol_interval_lexer.lpp"
{ return ')'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 497 "gaol_interval_lexer.lpp"
{ return ','; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 498 "gaol_interval_lexer.lpp"
{ return '+'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 499 "gaol_interval_lexer.lpp"
{ return '-'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 500 "gaol_interval_lexer.lpp"
{ return '*'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 501 "gaol_interval_lexer.lpp"
{ return '/'; }
	YY_BREAK
case 37:
#line 504 "gaol_interval_lexer.lpp"
case 38:
#line 505 "gaol_interval_lexer.lpp"
case 39:
#line 506 "gaol_interval_lexer.lpp"
case 40:
YY_RULE_SETUP
#line 506 "gaol_interval_lexer.lpp"
{ return gaol_read_number(gaol_text); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 507 "gaol_interval_lexer.lpp"
{ return gaol_read_number(gaol_text); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 508 "gaol_interval_lexer.lpp"
{ return gaol_read_uncertain(gaol_text); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 509 "gaol_interval_lexer.lpp"
{  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 510 "gaol_interval_lexer.lpp"
{ return UNEXPECTED_CHAR; /* Just to avoid stopping here */ }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 511 "gaol_interval_lexer.lpp"
ECHO;
	YY_BREAK
#line 1784 "lex.gaol_.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 128 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 128 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 127);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 511 "gaol_interval_lexer.lpp"


YY_BUFFER_STATE gaol_interval_parsing_buffer;
interval *gaol_result_of_parsing;
interval gaol_tmp_itv;
// Any error during the parsing?
bool gaol_global_parsing_flag;
extern int gaol_debug;

void gaol_initialize_parsing(const char* const s, interval* itv)
{
  gaol_interval_parsing_buffer = gaol__scan_string(s);
  gaol_result_of_parsing = itv;
  gaol_global_parsing_flag = false;
}

bool gaol_cleanup_parsing(void)
{
  gaol__delete_buffer(gaol_interval_parsing_buffer);
  return gaol_global_parsing_flag;
}

int gaol_wrap(void)
{
  return 1;
}

