#!/bin/sh
# Regenerates the lexer and the parser of the strings GAOL reads from their
# sources, gaol_interval_lexer.lpp (flex) and gaol_interval_parser.ypp (bison):
#
#   gaol/gaol_interval_lexer.cpp
#   gaol/gaol_interval_parser.cpp
#   gaol/gaol_interval_parser.h
#
# The three files are committed, and the three builds compile them without
# flex or bison. They are regenerated after a change of the .lpp or of the
# .ypp, with this script or with the target parser of the builds (cmake
# --build <build> --target parser, make parser, ninja parser), which runs the
# same commands:
#
#   sh gaol/regenerate_parser.sh
#
# FLEX and BISON give other programs than the flex and bison of the PATH. The
# committed files were generated by flex 2.6.4 and bison 3.5.1, which give
# them again byte for byte from the same sources; another version gives code
# that differs, and a warning says so. The programs run in a directory of
# their own, where they write lex.gaol_.c and y.tab.c, the names of the #line
# directives of the committed files.
#
# Copyright (c) 2026 ENSTA, France
#
# Created 2026-09-27 by Jordan NININ
set -e
gaol_dir=$(cd "$(dirname "$0")" && pwd)
flex=${FLEX:-flex}
bison=${BISON:-bison}
command -v "$flex" > /dev/null || { echo "regenerate_parser.sh: $flex not found (FLEX gives another)" >&2; exit 1; }
command -v "$bison" > /dev/null || { echo "regenerate_parser.sh: $bison not found (BISON gives another)" >&2; exit 1; }

flex_version=$("$flex" --version | head -1)
bison_version=$("$bison" --version | head -1)
case "$flex_version" in
  *" 2.6.4") ;;
  *) echo "regenerate_parser.sh: warning: $flex_version, not the flex 2.6.4 the committed lexer was generated with" >&2 ;;
esac
case "$bison_version" in
  *" 3.5.1") ;;
  *) echo "regenerate_parser.sh: warning: $bison_version, not the bison 3.5.1 the committed parser was generated with" >&2 ;;
esac

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cp "$gaol_dir/gaol_interval_lexer.lpp" "$gaol_dir/gaol_interval_parser.ypp" "$work"
cd "$work"
# The names of the lexer prefixed with gaol_ (-P), as those of the parser (-p),
# and the tokens of the parser in y.tab.h (-d). -y (yacc) writes y.tab.c and
# y.tab.h; -Wno-yacc because the parser is pure (%pure-parser), which POSIX
# yacc is not.
"$flex" -Pgaol_ gaol_interval_lexer.lpp
"$bison" -y -Wno-yacc -Wno-deprecated -Wno-other -d -p gaol_ gaol_interval_parser.ypp
cp lex.gaol_.c "$gaol_dir/gaol_interval_lexer.cpp"
cp y.tab.c "$gaol_dir/gaol_interval_parser.cpp"
cp y.tab.h "$gaol_dir/gaol_interval_parser.h"
echo "Regenerated gaol_interval_lexer.cpp ($flex_version), gaol_interval_parser.cpp and gaol_interval_parser.h ($bison_version) in $gaol_dir"
