#!/usr/bin/env python3
"""Builds todo_implement2.js: the table of the points (notes for each agent) + the workflow of todo_implement.js.

The table is the orchestrator's knowledge of TODO.md: which points make a chain (the second one is made on the
branch of the first because it changes the same code), what each agent should look at, how to validate."""
import json, re, sys

SCR = "/tmp/claude-1001/-home-jninin-Documents-WORK-DEV-GAOL-GAOL-V8/334ea319-d088-4702-9b10-e0628647c222/scratchpad"

P = {}


def point(id, slug, title, risk, notes, chain_note=None, validate=None, lenses=None, todo=None):
    P[id] = dict(id=id, slug=slug, branch="todo-" + slug, title=title, risk=risk, notes=notes.strip())
    if todo is not None:
        P[id]["todo"] = todo
    if chain_note:
        P[id]["chainNote"] = chain_note.strip()
    if validate:
        P[id]["validate"] = validate.strip()
    if lenses:
        P[id]["lenses"] = lenses


# ---------------------------------------------------------------------------------------------------------------
# The pilot (already run by todo_implement.js): 5, 7, 9, 14, 29, 44 (kept here for the bookkeeping only)
# ---------------------------------------------------------------------------------------------------------------

# The pilot points, implemented by todo_implement.js (kept here for the review-only runs and the bookkeeping)
point(5, "05-finite-math-only", "-ffinite-math-only is not refused", "high", "pilot")
point(7, "07-atanh-domain", "atanh([1, x]) is [DBL_MAX, +oo] instead of empty", "low", "pilot")
point(9, "09-tan-pi-half", "tan(interval(-M_PI_2, M_PI_2)) is [-oo, +oo]", "high", "pilot", lenses=["correctness"])
point(14, "14-exception-what", "gaol_exception does not redefine what()", "low", "pilot")
point(29, "29-ci-comma-locale", "the test under a comma locale does not run in the CI", "build", "pilot")
point(44, "44-cpack-stale-configure", "CPack's source archive does not see a stale configure", "build", "pilot")

# ---------------------------------------------------------------------------------------------------------------
# The pow chain: 1 -> 3 -> 2
# ---------------------------------------------------------------------------------------------------------------
point(1, "01-pow-norm-half", "the pow of the standard is written twice", "high", """
A refactoring with no change of results. gaol_ieee1788::pow (gaol/gaol_interval.cpp) intersects x with [0, +oo] and treats x = {0} apart, and gaol_pow_hybrid() does it again. The correction of the point: make the "standard" half of gaol_pow_hybrid() (the pow of Table 9.1 for an interval exponent) a function of gaol/gaol_interval.cpp; gaol_pow_hybrid() adds to it only the pown case of a degenerate integer exponent, and gaol_ieee1788::pow calls that half directly, except for its integer exponents beyond the ints. Keep the public API and the ABI as they are (no new public function, no new exported symbol unless the point really needs it: check with nm -D on the shared library and nm on the static one, before and after). Prior art, on an older base and with a much larger scope (public pown/pow_real/pow_hybrid API, function templates for gaol::pow, exact_string): the branch origin/todo-review-fixes, commits be03d16 and f6b02e0; read them for ideas and pitfalls, do NOT cherry-pick them (they do more than this point asks, on a base that has moved). The proof that nothing changed is a differential check: build the base library (a2ca992, in a separate worktree/build of your own under $SCR/build) and the new one, run the same program printing the hex bounds of gaol_ieee1788::pow, gaol::pow(interval, interval) and pow(interval, double/int) on a large grid (bases with 0, negative parts, infinite bounds, exponents degenerate or not, integer or not, huge, negative, NaN/empty; both builds sse and fpu), and diff the outputs. Keep a compact version of that grid in the suite as the regression test (in tests/ieee1788.cpp or where pow is tested, with the expected values written as hex literals taken from the base library, checked against mpmath where they are not trivially right): its teeth are shown by breaking the refactored function on purpose. The next points of the same chain (n° 3 then n° 2) are made on top of your branch.
""")

point(3, "03-pow-exact-corner", "pow(x, y) has the width of a double where the power at a corner is a double", "high", """
pow(x, y) has the width of a double where the power at a corner is a double. The lower bound is the double below CORE-MATH's value rounded upward, even when that value is exact: pow([4], 0.5) is [2 - 2^-52, 2], and the cases 149 to 152 and 163 of doc/compare/special_cases.md are wider than IEEE 1788's result for that reason alone. Correction: keep the value as the lower bound when the power is exact, as exp2, log2, nth_root(x, 3) and the functions of Table 10.5 do (read how they decide that a CORE-MATH value is exact: calling CORE-MATH in the downward and the upward direction, or another exactness test; choose the cheapest SOUND test: pow(x, y) is a hot function, an extra CORE-MATH call would double its cost, an exactness test that skips it for most inputs would not). Soundness: a value declared exact must be exactly the mathematical result, else the lower bound is wrong: verify against mpmath on many random inputs and on structured exact cases (perfect powers, 2^k, 4^0.5, 0.25^-0.5, 8^(1/3) which is NOT exact, huge and tiny results, subnormal results, infinite bounds). Update doc/compare/special_cases.md for the cases the point names (it is a table of results per library, produced with doc/compare/code: see how it is made and redo only what is needed, with clang-18 as the maintainer's reference compiler for that directory), doc/accuracy.md (the row of pow), the manual and the comments.
""", chain_note="""
Your base is the branch of point n° 1 (todo-01-pow-norm-half), which moved the standard half of pow into its own function: your change goes in that function.
""")

point(2, "02-rounding-check-once", "the rounding direction is still checked more than once", "high", """
The rounding direction is still checked more than once by some operations: pow(x, y) when it goes through exp(y log x) (an infinite bound, or a base starting at 0 with an exponent not above 0): log(), * and exp() check it three times; nth_root(x, q) for q < 0, which is inverse() of nth_root(x, -q): twice; modulo_k_pi(): twice. Correction: call the bodies of these operations after a single check, as tan(), the relational functions and the negative powers (uipow_rounded_upward(), interval::inverse_upward()) now do; the bodies of log(), exp() and * without the check remain to be written. Read gaol/gaol_fpu.h (GAOL_RND_ENTER, round_upward_if_needed: the comments at its top explain the design: the direction is left upward and checked once per function that users call) and how commit f350a42 did tan(), acos_rel() ... (git show f350a42) to follow the same idiom. * exists in both builds (gaol_interval_sse.cpp and gaol_interval_fpu.cpp): the body without the check must exist in both. Prove that the check happens once per call of a public function, for example with a counter compiled only in a test build, or by inspection plus a debug assertion; timing is secondary and only meaningful when the machine is quiet (check uptime): do not report timings taken while other builds run. The results must be bit-identical before and after on a large grid (differential check against a build of the base commit a2ca992, in both builds). Keep the ABI (no exported function disappears).
""", chain_note="""
Your base is the branch of point n° 3, itself made on point n° 1: the exp(y log x) path of pow is in the function that point n° 1 made.
""")

point(8, "08-pow-large-n", "pow(x, n) for large n", "high", """
Review n° 7 (section 5 and Appendix B item 7 of examples/examples.md), plus a second part the review did not correct. (1) ipow_exact_dn() loses the square of the remainder: `nl = std::fma(-h,h,p) + nl*(2.0*h - nl);` keeps it. Test (tests/arithmetic.cpp): pow([1.0000001], n) for n = 2^28 - 1, 2^31 - 1 and 2^32 - 1 against the tightest bounds computed with mpmath (check that the manual's promise, the tightest bound or one double beyond, then holds; also n = 2^28, 2^30, negative n, other bases, bases near 1, and n up to INT_MAX). (2) Where the power of a bound leaves the range of doubles (towards 0 or towards infinity), both bounds take rounded products, which the SSE2 and FPU builds multiply in different orders: their bounds differ in 190 random cases out of 1600, against "the same bounds on every machine" of doc/accuracy.md. Make them agree, or say so there. Prefer making them agree (soundness and reproducibility) if it can be done without slowing the ordinary path; if the only fix costs more than it is worth or is unsound, document the difference in doc/accuracy.md and say why. Find where pown is computed (gaol_interval.cpp, gaol_interval_sse.cpp, gaol_interval_fpu.cpp). Build both variants (sse and fpu) and compare their outputs on the same random cases: a program printing hex bounds, run with both builds, diffed.
""")

# ---------------------------------------------------------------------------------------------------------------
# Bounds
# ---------------------------------------------------------------------------------------------------------------
point(4, "04-ftz-daz", "flush-to-zero and denormals-are-zero make the bounds wrong", "high", """
Review n° 2 (section 5 and Appendix B item 2 give the code and the test). Flush-to-zero and denormals-are-zero make bounds wrong: with them [1e-300] * [1e-20] is [0, 0]. Three parts, all in the point: (a) probe with a subnormal in round_upward_if_needed() (gaol/gaol_fpu.h) where GAOL_RND_SSE_REGISTER is defined, and clear FTZ and DAZ in MXCSR (& ~0x8040); (b) pass -mno-daz-ftz (which stops GCC linking crtfastmath.o) in the link options of gaol.pc and of gaol::gaol where the compiler accepts it (GCC 12 and later on x86; GCC 9.4 and Clang 18 refuse it: test the flag with the compiler at configure time in the three builds: CMake with check_cxx_compiler_flag or a link check and INTERFACE_LINK_OPTIONS of gaol::gaol and the gaol.pc CMake writes; meson; autotools: keep the three alike); (c) say in doc/using.md, doc/three-builds.md and the manual (manual/v5/gaol.tex) that linking with -Ofast, -ffast-math or -funsafe-math-optimizations, or loading code compiled with them (a plug-in, a Python module), makes the bounds wrong. The probe runs in every operation: its cost is a concern of the point ("à mesurer d'abord sur les processeurs de l'intégration continue": an addition with a subnormal operand is slow on some x86 processors). Measure on this machine (i7-1185G7) only when it is quiet (uptime) with clang-18: x + y, exp, sin, with and without the probe; think about other processors and prefer the design whose worst case you can bound (for example a probe that never executes an arithmetic instruction with a subnormal input on the fast path, if a sound one exists); say what you measured and what you could not. The test of Appendix B item 2 (tests/rounding_direction.cpp, SSE2 only) sets FTZ, DAZ and both with _mm_setcsr and checks the tightest enclosures of [1e-300]*[1e-20], [3e-308]-[2.9e-308], sqr([1e-160]) and [100*2^-1074]*[1e10]; write it (restore MXCSR afterwards, RAII), and note that nothing here can test -mno-daz-ftz (GCC 12+ only). x86 only: code and test are guarded; the ARM equivalent (the FZ bit of FPCR) is out of scope unless it is trivial (no ARM machine here: say so).
""")

point(6, "06-fegetround-mxcsr", "pow misses a subnormal result when the x87 unit and MXCSR disagree", "high", """
Review n° 3 (section 5 and Appendix B item 3). On x86-64 with glibc, pow misses a subnormal result when the x87 unit and MXCSR disagree (x87 rounding to nearest, MXCSR upward, as the exactinit() of Shewchuk's and Triangle's predicates leaves them): 205 random cases out of 400. CORE-MATH rounds these results itself, in the direction fegetround() gives, which glibc reads from the x87 unit. Correction: in gaol/core_math_port.h (forced into every CORE-MATH source), on x86-64, define fegetround() as a read of MXCSR (after <fenv.h> is included), as CORE-MATH's own get_rounding_mode() does in rsqrt.c, asinpi.c and cbrt.c; the vendored sources stay unchanged. Add to tests/rounding_direction.cpp (which already lists this state: read how it iterates over the states) pow with subnormal results: Appendix B item 3 gives gaol_ieee1788::pow(interval(0x1.4a1249ba9b6d5p-1), interval(0x1.97f9e85175cf7p+10)) and asks for two more with subnormal results; "to nearest, and upward for SSE" fails 6 checks without the fix. Think about the other platforms that compile this header: i386 (GAOL computes with SSE2 there too: does the same disagreement exist? the fix may apply to i386 with __SSE2_MATH__ as well, but nothing here can test 32-bit: decide, guard and say so), macOS x86_64 (does its fegetround already read MXCSR?), MinGW-w64 and Visual C++ (see gaol/gaol_config.h and doc/three-builds.md for the MinGW versions that are refused because their fegetround answers from a state of its own), musl, and the fact that fegetround may be a macro. What you define must not change what code other than CORE-MATH's sees.
""")

point(10, "10-hausdorff-nb-fp", "hausdorff() on infinite bounds, nb_fp_numbers() on -0", "low", """
Review n° 19 and n° 20 (section 5 and Appendix B items 19 and 20). hausdorff(x, x) is +oo for x = [1, +oo], and so is hausdorff([1, +oo], [2, +oo]) whose distance is 1: a fixed-point loop on a box with an unbounded side never stops. Correction, in BOTH builds (gaol/gaol_interval_sse.cpp:93 and gaol/gaol_interval_fpu.cpp:28; also the contract comment in gaol_interval.h): equal bounds, infinite ones included, are at distance 0; Appendix B item 19 gives the expression. nb_fp_numbers(-0.0, 1.0) goes round the clock and is 13830554455654793217, and [1, 2] - 1 has -0 as lower bound: number the doubles by the bits of std::fabs(a) and std::fabs(b) (Appendix B item 20 gives the expression). Tests in tests/other_functions.cpp: hausdorff([1,+oo],[1,+oo]) == 0, hausdorff([1,+oo],[2,+oo]) == 1, hausdorff([1,+oo],[1,2]) == +oo, and the other combinations of infinite bounds (see the FPU code's comment about hausdorff([-oo,+oo],[-oo,+oo])); nb_fp_numbers(-0.0, 1.0) and nb_fp_numbers(-1.0, 0.0) are 4607182418800017409; check +0 and -0 in every argument position. Run the tests in both variants (sse and fpu): the two builds must agree.
""")

point(11, "11-lexer-subnormal", "the reader gives a wrong subnormal enclosure with flush-to-zero and denormals-are-zero", "high", """
The reader gives a wrong subnormal enclosure with flush-to-zero and denormals-are-zero: textToInterval("1e-310") is [0x0.fffffffffffffp-1022, 0x1p-1022], which does not contain 1e-310 (GAOL was stuck there before the bisection on the bits). gaol_compare_number() (gaol/gaol_interval_lexer.lpp) tests !(x > 0.0) and takes std::frexp() of the candidate double, which DAZ reads as 0. Correction: take the exponent and the mantissa of the candidate from its bits. The committed generated file gaol/gaol_interval_lexer.cpp must be regenerated exactly as the project does it: `cmake --build <build> --target parser` (gaol/regenerate_parser.sh does the same without CMake; the flex 2.6.4 and bison 3.5.1 installed here are the versions of the committed files: the diff of the generated file must be only the consequence of your .lpp change; check with git diff --stat that the parser files did not change). The tool writes into the sources of your worktree: that is intended; commit the generated files that changed. Test in tests/numbers.cpp: with MXCSR FTZ/DAZ set through _mm_setcsr (x86 only, restored afterwards, RAII) textToInterval("1e-310"), "5e-324", "2.5e-324", "1e-320", "2.2250738585072011e-308" enclose the exact decimal value (exact comparison in the test: compare with exact integer/rational arithmetic, not with strtod) and are the tightest enclosures. Point n° 18 of the same chain (reading a long number under a comma locale) modifies the same functions afterwards and is made on top of your branch.
""")

point(18, "18-reader-locale-speed", "reading a long number under a comma locale is slow", "high", """
Reading a long number under a comma locale is slow: each of the at most 125 comparisons of gaol_enclose_number() parses the text again, in a time quadratic in its length: 2.5 s for 20000 characters against 0.08 s under the C locale. Correction (two options in the point): parse the mantissa and the exponent once and compare them with each double, or give strtod() a copy of the text with the decimal separator of localeconv() so that its value is right again and two comparisons suffice. Read gaol_enclose_number() and gaol_compare_number() (gaol/gaol_interval_lexer.lpp, which point n° 11 just changed: you work on top of it) and Appendix B item 9 of examples/examples.md (the reading under a comma locale and its test, already applied: the steps doubling from strtod()'s value and the bisection on the bits). Choose the option that keeps the result identical to the C locale and is provably sound; make it linear in the length of the text. Regenerate the lexer as point n° 11 did (cmake --build <build> --target parser; commit the generated file). Test in tests/numbers.cpp under fr_FR.utf8 (installed here; skipped where no comma locale exists): a 20000-digit number reads in well under a second (use a generous CTest TIMEOUT so that a slow CI machine does not flake) and gives the same enclosure as under the C locale; also the special forms (hexadecimal floats, exponents, the uncertain form 1.5?1). Teeth: without the fix the reading takes seconds; the TIMEOUT or a comparison of the two locales' durations with a large tolerance shows it.
""", chain_note="""
Your base is the branch of point n° 11 (todo-11-lexer-subnormal), which changed the same functions and regenerated gaol/gaol_interval_lexer.cpp.
""")

# ---------------------------------------------------------------------------------------------------------------
# Crashes
# ---------------------------------------------------------------------------------------------------------------
point(12, "12-long-sums", "long sums overflow the stack", "high", """
Review n° 17 (section 5 and Appendix B item 17). A sum of 100000 terms read from a string, and expressions as long built through the API, recurse once per term in the evaluation and in the destruction of the tree and overflow the stack. Correction: (a) in gaol/gaol_interval_parser.ypp fold each binary operation when it is read (`$$ = gaol_leaf(gaol_value($1) + gaol_value($3))`), as function calls already are, and regenerate the committed parser (`cmake --build <build> --target parser`; flex 2.6.4 and bison 3.5.1 installed here are those of the committed files; commit gaol_interval_parser.cpp/.h only if they change); (b) for the expressions of the API (gaol/gaol_expression.h, gaol_expression.cpp, gaol_expr_eval.h, gaol_expr_visitor.h): an evaluation and a destruction without recursion (explicit stack; the destruction of a long chain must not recurse). Keep the results bit-identical (order of evaluation and associativity unchanged) and the reference counting (the shared null node is immortal: see git log). Tests (tests/expressions.cpp): a sum and a product of 200000 terms read from a string and built through the API, evaluated and destroyed; they overflow the default 8 MB stack without the fix (prove it) and the test must be deterministic: a test that only "crashes without the fix" must also run in the CI's sanitizer jobs, where stack frames are larger: consider running the check on a thread with a chosen small stack (pthread_attr_setstacksize on POSIX, skipped elsewhere). Run the whole suite also with -fsanitize=address,undefined. Also think about deeply nested parentheses "((((...))))" and chains of unary minus: what does the grammar do with them (a parser stack limit YYMAXDEPTH may apply): say what happens and document the limit if there is one.
""")

# ---------------------------------------------------------------------------------------------------------------
# Streams and text: 13 -> 16 -> 17, and 15
# ---------------------------------------------------------------------------------------------------------------
point(13, "13-point-interval-text", "a point interval is written in a form the reader refuses", "low", """
Review n° 12 (section 5 and Appendix B item 12). A point interval is written in a form the reader refuses: `<0.1, 0.1000000000000001>` in the default format ("bounds of degenerate interval do not evaluate to the same value"), so textToInterval(intervalToText(interval(0.1))) is the empty set, contrary to the manual. Correction: in display_bounds() (gaol/gaol_interval.cpp:708) write `<a, a>` only when the two texts are equal (`l == r && left == right` in Appendix B item 12) and `[l, r]` otherwise; correct the manual (manual/v5/gaol.tex) where it shows `<0.1, 0.1000000000000001>` (grep), and doc/*.md. Tests: in tests/numbers.cpp, for special values and every precision, the text of a point interval reads back and encloses it (intervalToText then textToInterval); in tests/ieee1788.cpp, textToInterval(intervalToText(interval(0.1))) contains 0.1. Check what the other formats do for point intervals. Points n° 16 and n° 17 of TODO.md (the formats, the speed of operator<<) work on the same code afterwards, on top of your branch.
""")

point(16, "16-display-formats", "the width and center formats", "high", """
Review n° 21. The width and center formats display a center and a radius rounded to nearest, which do not necessarily contain the interval ([1, 1 + 2^-52] is written `1 (+/- 1.11e-16)`), and a radius of zero for [0, 5e-324], contrary to the manual; the manual and gaol/gaol_interval.h describe the width format as the center and the width while it prints the radius. Both formats write the empty set `empty` where the manual says that all formats write `[empty]`. gaol_ieee1788::intervalToText follows the global format and the locale of the stream, so its text is not always a literal of IEEE 1788. Correction (the point offers two): document the two formats as display formats, or round their radius upward; make intervalToText write the bounds format, with a point. Decide for each of the three issues and justify: (i) radius rounding: rounding the radius upward while the center is rounded to nearest makes the displayed pair enclose the interval only if the center's rounding error is included: compute the radius so that [center - radius, center + radius] provably contains the interval, or document these formats as approximate displays; prefer the enclosing display since GAOL is about enclosures, unless it makes the text worse than the maintainer would accept: then document; (ii) the text of the empty set (make code and manual agree: which is right per IEEE 1788-2015 12.11?); (iii) intervalToText independent of the global format, of the precision and of the stream's locale. Read IEEE 1788-2015 12.11 (text input/output: the inf-sup and the uncertain forms `m?r`) and the functions of gaol_ieee1788. The formats are documented in doc/using.md, doc/accuracy.md, manual/v5/gaol.tex and gaol/gaol_interval.h: make all of them say what the code does. Tests in tests/numbers.cpp / tests/ieee1788.cpp / tests/input_output.cpp: the displayed radius encloses (every precision, special values, subnormals, huge), the empty set prints as documented, intervalToText is independent of the global format, the precision and the locale (comma locale: fr_FR.utf8 is installed here). Do not make operator<< slower than needed: point n° 17 works on its speed after you.
""", chain_note="""
Your base is the branch of point n° 13 (todo-13-point-interval-text), which changed display_bounds().
""")

point(17, "17-output-speed", "operator<< is slower since it writes into an ostringstream of its own", "high", """
operator<< is about 450 ns slower per interval since it writes into an std::ostringstream of its own (13 % for the bounds format, 2.2 times for the center format), and std::internal now pads like std::right. To be measured on programs that write many intervals; formatting into a character buffer rather than a stream would save most of it. This is an optimization with a correctness risk: the text must stay byte-identical (bounds are rounded OUTWARD when printed in decimal; the stream's precision, flags, fill, width, adjustfield, locale (decimal point and grouping of the stream's locale, imbue), showpos, uppercase, hexfloat, fixed/scientific must behave as they do now; std::internal is a regression to fix: see what it did before, `git log -p` on operator<<, commit 841cdbd "operator<< writes each interval at once", and decide what it should do). Method: (1) write a benchmark writing 1e6 intervals in each format (bounds, width, center, hexa...) and time it with clang-18 and gcc, on a quiet machine only (check uptime; if other builds are running, say the timings are indicative); (2) write a differential harness printing many intervals (random doubles, special values, every format, precisions 0 to 20, widths, fills, adjustments, flags, the C and the fr_FR.utf8 locales) with the OLD operator<< (the branch you are based on, in a separate build) and the NEW one and comparing byte for byte; (3) implement the buffer version only if it is measurably faster (say by how much) and byte-identical; otherwise report that it is not worth it (status "not-actionable", with the measurements): a change that makes output faster and subtly wrong is worse than none. Keep using the stream's locale facets (numpunct) for the decimal point. Point n° 16 (the formats) was made just before on the same code: you work on top of it. Keep a differential test in the suite only if it is compact and deterministic.
""", chain_note="""
Your base is the branch of point n° 16 (todo-16-display-formats).
""")

point(15, "15-extract-empty-line", "operator>> throws on an empty line", "low", """
operator>> throws on an empty line, and on `in >> d >> x` where the interval reads the empty rest of the line of the number: a file ending with an empty line ends `while (in >> x)` with input_format_error. Correction: read with std::getline(is >> std::ws, buffer), which skips the blanks as the reading of a number does, or say in the manual that an empty line is ill-formed (prefer the code fix). Reading an interval by word rather than by line would also allow re-reading what `os << x << ' ' << y` writes: intervals can contain spaces ("[1, 2]"), so a word-based reader is not simple: do only what the point's first correction says unless you find the word-based one is clean and small, and record the discussion in open_questions. Look at operator>> in gaol/gaol_interval.cpp and Appendix B item 14 of examples/examples.md (the earlier fix: failbit, end of input). Careful: `is >> std::ws` skips newlines too, so an interval text spread over lines, or "[1, 2]\\n\\n[3, 4]", must behave sensibly (a blank line between two intervals is skipped, as a blank between two numbers is); what happens with a line holding only spaces; with std::noskipws set on the stream (it must not make well-formed input accepted differently: think about it and test it); with failbit/eofbit at the end of the input, and with exceptions() masks on the stream. Tests in tests/input_output.cpp (or numbers.cpp): `while (in >> x)` over "[1, 2]\\n[3, 4]\\n\\n" reads 2 intervals and throws nothing; `in >> d >> x` over "1.5 [1, 2]\\n", "1.5\\n[1, 2]\\n" and "1.5\\n"; an empty stream gives failbit and no exception (check what `double` does at the end of the input and be consistent).
""")

# ---------------------------------------------------------------------------------------------------------------
# Headers
# ---------------------------------------------------------------------------------------------------------------
point(19, "19-ieee1788-expression-header", "gaol::sin(0.5) no longer compiles", "high", """
Review n° 16 (section 5 and Appendix B item 16). gaol::sin(0.5) no longer compiles: every function of the namespace gaol on a double is ambiguous between the overloads for intervals and for expressions since gaol_ieee1788.h includes gaol_expression.h; GAOL 4 compiled it. Correction: stop including gaol_expression.h from gaol_ieee1788.h, and move the two expression overloads of gaol_ieee1788 (pown(e, n), pow(e1, e2)) to the end of gaol_expression.h; a program that uses expressions includes gaol_expression.h, as with GAOL 4. Test (tests/other_functions.cpp): static_assert(std::is_same<decltype(gaol::sin(0.5)), interval>::value, "") for the functions of the namespace gaol taking an interval and given a double, and a compile-only test that programs including the headers in every order (gaol_ieee1788.h then gaol_expression.h, the reverse, gaol.h alone) compile and resolve the overloads alike (several translation units, or a set of static_asserts). Check every file of the tree that got gaol_expression.h through gaol_ieee1788.h and now needs to include it itself (gaol/, tests/, examples/, check/, doc/compare/code, the docs' programs). Document which header to include for expressions (doc/using.md, the manual). Check that gaol::sin(0.5) compiles as C++11 to C++20 with GCC and Clang.
""")

point(20, "20-header-hygiene", "the public headers overflow into the program", "high", """
Review n° 22 (section 5). The public headers overflow into the program. gaol_interval_parser.h, installed, does not compile when included, and it and gaol_init_cleanup.h are internal; gaol_allocator.h does not compile alone. They put `using std::exception; using std::string;` at global scope and define macros without a prefix (INLINE, HAVE_FENV_H, MEMALIGN, __HI...). With -Wall -Wextra and a plain -I (pkg-config, or FetchContent, whose include directory is not SYSTEM), a program gets about 35 warnings: 30 -Wunused-parameter in gaol_expr_visitor.h, and a -Wdeprecated-copy at each `x = ...;` (a user-written copy constructor with an implicit copy assignment). Correction: stop installing the internal headers (in the three builds: the CMake install lists, Makefile.am, gaol/meson.build), remove the `using`s, prefix the macros, declare the copy assignment as default, leave the unused parameters unnamed. Method: (1) write a compile check that includes every installed header alone (one translation unit per header, with -Wall -Wextra -Wconversion -Wpedantic, as C++11 and C++17, GCC and Clang) and a program using GAOL with -Wall -Wextra: it must give zero warnings and leak no macro (list the macros with -dM -E before/after and compare with a list of allowed GAOL_-prefixed ones); make it a test of the suite (tests/fp_strict, tests/find_package and tests/fetch_content are examples of tests that build other programs), (2) fix. The internal headers may still be needed by installed ones (check the include graph; if an installed header includes an internal one, that one stays installed or the include goes). The macros are used all over gaol/*.cpp: renaming is mechanical but must not change behaviour (build all variants; the generated parser files include some macros: gaol_interval_parser.ypp/gaol_interval_lexer.lpp and their committed .cpp/.h must be regenerated with `cmake --build <build> --target parser` if you touch them: keep such edits to the minimum and say if you did). Removing the `using std::...` may break sources that relied on them: qualify with std::. ABI: no exported symbol may change (nm -D before/after on the shared library). Points n° 19 (the include structure of gaol_ieee1788.h and gaol_expression.h) and others touch these headers too: keep your edits to what your point needs.
""")

# ---------------------------------------------------------------------------------------------------------------
# Interface
# ---------------------------------------------------------------------------------------------------------------
point(21, "21-integer-constructors", "integers beyond 2^53", "high", """
Integers beyond 2^53: `interval(0)`, `interval(0, 0)`, `x = 0`, `x < 0`, `max(x, 0)` and `T(0)` compile, GAOL v5 having no constructor from strings any more: the integer becomes a double. An integer beyond 2^53 thus becomes a double that does not contain it. Correction: constructor templates on the integer types, constrained (the point says it was checked on all the test programs and the sources of the library; in headers, with no ABI change). Not a plain interval(int), which makes interval(5L) ambiguous. Design: interval(n) for an integer n beyond 2^53 must CONTAIN the integer: the two neighbouring doubles, lower bound the largest double <= n and upper bound the smallest >= n, a point interval when n is representable. The same for the two-argument constructor (lower bound rounded down, upper bound rounded up), for assignment (x = n), for the comparisons and functions taking an integer (x < 0, max(x, 0): see which overloads exist, those taking a `double` today), and for T(0) in generic code. Mind the house rules: the constructors of interval are explicit and a double becomes an interval only where the program writes interval(d): `x = 0` and `x < 0` currently compile through some path: find out exactly which (grep operator=, the relation operators, the max/min overloads) and keep the set of accepted expressions the same, changing only what happens to big integers (do not make new expressions compile, do not stop old ones compiling). Care with signed/unsigned/long/long long/__int128 types, char and bool (do not accept bool and char by accident), enums, overload ambiguity with double and with the existing constructors, the ABI (templates in headers, no exported symbol changes) and C++11 (no if constexpr, no concepts: SFINAE with std::enable_if and std::is_integral). Tests in tests/constructor.cpp (and assignment.cpp, relations.cpp...): every integer type at 0, 1, -1, INT_MAX, LLONG_MAX, LLONG_MIN, ULLONG_MAX, 2^53, 2^53+1, 2^64-1: the interval contains the integer exactly (check with exact integer arithmetic, for instance long double or unsigned __int128 where available, or exact decimal strings with mpmath), and is a point interval when the integer is representable; static_asserts that interval(5L), interval(5u), interval(5ull) are unambiguous.
""")

point(22, "22-container-order", "no total order for containers", "high", """
No total order for containers. <, <=, > and >= are the "certainly" relations of IEEE 1788, true for (empty, empty): std::set loses the overlapping intervals, and std::sort of a vector containing an empty interval reads beyond its end. Correction: a gaol::lexicographic_less (perhaps a specialization of std::less: consider whether specializing std::less<gaol::interval> is wise: it is allowed for a user type and would make std::set<interval> and std::map work by default, but it changes silently what containers of intervals mean; decide and say why), and a warning in the documentation against std::sort, std::set, std::max, std::min and std::clamp without a comparator. Design: a strict weak ordering on intervals: compare the lower bounds, then the upper bounds, the empty set first (or last: choose, document); it must be a strict weak order including empty vs empty (equivalent) and -0.0 vs +0.0 (equivalent: compare with < on doubles), and no NaN problem: the empty set has NaN bounds in GAOL v5, so the comparator tests is_empty() explicitly. Header-only, public, documented in the Doxygen comments, doc/using.md (a section "Intervals in containers") and the manual, where the relations are described. Tests in tests/relations.cpp (or a suitable one): the strict weak order axioms checked exhaustively on a set of about 50 special intervals (irreflexivity, asymmetry, transitivity, transitivity of equivalence); std::sort of a vector containing empty intervals is correct under it; std::set<interval, gaol::lexicographic_less> keeps overlapping intervals; std::map works. The out-of-bounds read of std::sort with the raw operator< is undefined behaviour: show it in the documentation, not in the suite.
""")

point(23, "23-rounding-guard", "managing the rounding direction", "high", """
Managing the rounding direction. cleanup() restores it only once, there is no scoped guard, and rnd_keep() is not presented as a barrier. Correction: a gaol::restore_rounding() that can be called as many times as one wants, a guard that computes a block in round-to-nearest (about 7 ns), and rnd_keep() documented. Read gaol/gaol_init_cleanup.h, gaol_fpu.h and the documentation of init/cleanup (doc/using.md, manual/v5/gaol.tex; GAOL leaves the rounding direction upward between operations unless GAOL_PRESERVE_ROUNDING; cleanup() restores the direction the program started with; every complete program in the docs ends with gaol::cleanup()). Design (say what you chose and why in your report): (a) gaol::restore_rounding(): sets back the direction that was in effect when GAOL initialized (the program's direction), idempotent, callable any number of times, cheap; what it does in GAOL_PRESERVE_ROUNDING builds (a safe no-op: define it); the rounding mode is per thread: document; (b) a scope guard (RAII: for instance gaol::rounding_guard or gaol::scoped_nearest) whose constructor sets round-to-nearest (on x86 with SSE2 MXCSR only, consistently with how GAOL sets it) and whose destructor puts back upward (the state GAOL keeps), so that a block of the program's own floating-point code runs in nearest without leaking; nesting must work; an exception must not leak the state; (c) rnd_keep(): find what it is (grep: the barrier against compilers moving floating-point operations across a change of direction, see the notes on -frounding-math in gaol_fpu.h) and document it in doc/using.md and the manual as the barrier. Measure the cost of the guard (about 7 ns is the point's estimate) with clang-18 on a quiet machine; check that the direction is nearest inside and upward outside with fegetround() and _mm_getcsr(), in tests/rounding_direction.cpp (which already lists the states), also with GAOL_PRESERVE_ROUNDING (a second build: -DGAOL_PRESERVE_ROUNDING=ON), with nesting, exceptions, and threads. Put the API in gaol_init_cleanup.h or the header where init/cleanup live; documented (Doxygen, doc/using.md, the manual).
""")

point(24, "24-fp-exceptions", "floating-point flags and exceptions", "low", """
Floating-point flags and exceptions. With hardware exceptions enabled (feenableexcept), 1/[0,1], log([0,1]), [1e308]*10 and every is_empty() of a computed empty set die on SIGFPE: the unbounded results come from overflows or divisions by zero, and is_empty() compares NaN bounds with a signaling comparison. Every operation raises the inexact flag. Correction: is_empty() with std::islessequal, at no cost, and a word in the documentation saying that hardware exceptions must be disabled. Find every place that decides emptiness with a comparison on NaN bounds (is_empty() inline in gaol/gaol_interval.h, its overloads, the comparisons in gaol_interval_sse.cpp/gaol_interval_fpu.cpp: grep isnan, is_empty, `!(`), and make the ones the point names use std::islessequal (or an equivalent quiet comparison) at no measurable cost (compare the assembly of is_empty() before and after with clang-18 -O3 and gcc -O3; micro-benchmark on a quiet machine); is_empty() is inline in a header: no ABI change. Test: a program (tests/, POSIX/glibc only: guard with the availability of feenableexcept; run the check in a child process (fork) or with a SIGFPE handler and sigsetjmp so that without the fix the test fails cleanly instead of killing the runner; Windows and macOS skip and the test says so) that enables FE_INVALID, computes empty sets (an empty intersection, sqrt of a negative interval, [1,2] & [3,4], interval::emptyset()) and calls is_empty() on them, in both builds sse and fpu. Documentation (doc/using.md, doc/accuracy.md if it fits, manual/v5/gaol.tex): hardware floating-point exceptions must be disabled while GAOL computes (1/[0,1], log([0,1]) and [1e308]*10 raise divide-by-zero or overflow legitimately) and every operation raises the inexact flag (fetestexcept() cannot detect anything about GAOL results). Do not try to make the other operations trap-free: that is the documentation part of the point.
""")

# ---------------------------------------------------------------------------------------------------------------
# The three builds
# ---------------------------------------------------------------------------------------------------------------
point(41, "41-meson-subproject", "GAOL cannot be a meson subproject", "build", """
GAOL cannot be a meson subproject: meson.build calls add_global_arguments (17 times, from line 171), which meson refuses in a subproject: a parent project doing subproject('gaol') stops on "Function 'add_global_arguments' cannot be used in subprojects", with meson 0.53.2 (installed here) as with 1.11.2. The comment of gaol_dep (gaol/meson.build) says it is meant for a meson project that takes GAOL as a subproject. Correction: add_project_arguments, and put in the compile_args of gaol_dep the options the code using GAOL needs (-frounding-math, -ffp-contract=off..., those of gaol.pc), which the arguments of the project do not pass on to the parent project; or remove the promise of the comment. Prefer making the subproject work, with a test: a check that builds a tiny meson parent project whose subprojects/gaol is the tree (symlink or wrap) and links a program that uses interval arithmetic; add it to .github/workflows/build-systems.yml if that is where the meson checks live (read it; add no long job: a step in an existing meson job), and to the meson tests if it can be a test there. Test locally with meson 0.53.2 (the CI uses a recent meson from pip: mind the differences, e.g. add_project_arguments(..., language: 'cpp'), dependency objects, meson.is_subproject()). Keep the standalone meson build equivalent in behaviour: the same flags for GAOL's own compilation (compare `meson introspect --targets` or compile_commands.json before and after; the tests and examples built in the standalone build must get the same flags) and the same installed files and gaol.pc. Documentation: the meson section of doc/building.md, and doc/using.md if it has a meson recipe.
""")

point(42, "42-meson-windows-python", "meson 0.53 on Windows can take the fake Python of the Microsoft Store", "build", """
meson 0.53 on Windows can pick the fake Python of the Microsoft Store: find_program('python3', 'python', native: true), which reads VERSION.txt in project(), can find the python3.exe of WindowsApps, which only opens the Store and which meson 0.53 does not discard: run_command fails and meson setup stops. Not reproduced (no Windows here); the CI is not touched, its meson coming from pip and being recent. Correction: look for python before python3 on Windows, or say so in the meson section of doc/building.md. Prefer the code change if it is safe on every platform (the order of the arguments of find_program is the order of preference; on Linux `python` may be Python 2 or absent, so the order must depend on the platform: build_machine.system() == 'windows', since it is a native program), and document it in doc/building.md too. You cannot test on Windows: reason from the source of meson 0.53 (installed: `python3 -c "import mesonbuild; print(mesonbuild.__file__)"` says where; does 0.53 have any check for WindowsApps? read find_program) and test on Linux that the order change does not change which program is found and that `meson setup` still works with meson 0.53.2. The change is tiny: touch nothing else in meson.build.
""")

point(43, "43-version-bom", "a VERSION.txt that begins with a byte order mark", "build", """
A VERSION.txt that begins with a byte order mark (UTF-8 with BOM, as some Windows editors save it) is refused by the three builds with `VERSION.txt holds "7.3.11"`, the offending character being invisible. Correction: strip a leading byte order mark before reading the version, or say in the message that the file must hold only digits and dots. Prefer stripping the BOM in all three builds (CMake: file(READ) then a check of the first bytes (file(READ ... HEX) works) before project(); meson: the Python one-liner in project() (open with encoding 'utf-8-sig'); configure.ac: how it reads the file (m4_include? sed? tr?)): read the code of each first (CMakeLists.txt before project(), meson.build's project(), configure.ac and the generated configure) and doc/building.md's section "The version of GAOL", which says what each build accepts and must say that a BOM is ignored (and what else: blanks, empty lines, CRLF line endings? test CRLF too and fix it the same way if it fails: a Windows editor that adds a BOM often uses CRLF: test both, report). If you change configure.ac, regenerate configure exactly as doc/building.md says (autoconf 2.72 and `AUTOHEADER=true autoreconf`, without --force --install) and commit the regenerated configure: the CI compares `configure --version` with VERSION.txt. Test: run each build's version reading on a temporary copy of the tree whose VERSION.txt has a BOM (and one with BOM and CRLF): `cmake -S copy -B build` (configure step only), `meson setup` (0.53.2 here) and ./configure --version / config.status in a temporary directory; a CTest test in tests/ if a cheap one is possible (a cmake -P script), else a step in .github/workflows/build-systems.yml and a manual procedure recorded in your report. If cheap, make the error message for an invalid file show the offending bytes visibly (hex).
""")

# ---------------------------------------------------------------------------------------------------------------
# Documentation
# ---------------------------------------------------------------------------------------------------------------
point(39, "39-goldstein-price", "the Goldstein-Price function of the manual forgets the +1", "high", """
The Goldstein-Price function of the manual forgets the +1 ((x + y)^2 instead of (x + y + 1)^2), like examples/16_Goldstein_Price.cpp, the example of GAOL 4, and the manual says that f "runs through" the enclosure, which is about 150 times wider than the image of the true function. Correction: say that the enclosure contains the image, and give the true function or say that it is not it. The true function is f(x,y) = [1 + (x+y+1)^2 (19 - 14x + 3x^2 - 14y + 6xy + 3y^2)] [30 + (2x-3y)^2 (18 - 32x + 12x^2 + 48y - 36xy + 27y^2)]; on [-2,2]^2 its minimum is 3 at (0,-1); compute the true image, the natural interval extension and the subdivided ones with mpmath and exact arithmetic yourself. Give the true function (in the manual and in examples/16_Goldstein_Price.cpp, a self-checking example built and run by the CI: change its checks accordingly, with values computed by exact arithmetic, and keep the example's teaching purpose (naive evaluation against bisection: the width of the enclosure) true) and rewrite the sentence of the manual about what the enclosure is: it contains the image, and it is wider than it because of the dependency problem. Look at what examples/examples.md and doc/*.md say about it too (grep Goldstein). manual/v5/gaol.tex only: manual/v4 is GAOL 4's and stays as it is. The example is compiled and run by ctest: run it in the variants; the manual must compile.
""")

point(40, "40-small-errors", "small errors", "high", """
Small errors, all named in the point: (1) the header comment of chi() (gaol/gaol_interval.h) says chi([0,0]) = 0 where the code and the manual say -1 (read the code, the manual and IEEE 1788-2015 if it defines it; make the comment true); (2) tests/gaol_tests.h says the references use 400 bits where tests/elementary_values.py uses 2000 (check all the *_values.py generators for their precision and fix the comment(s) to say what is true); (3) the comment of interval(const char*) names a jail_parser.h that does not exist: interval(const char*) was removed (commit 373d35e), so grep for jail_parser and for any other remaining reference to a removed constructor and fix what is still wrong; (4) GAOL_NODISCARD works from C++17 and gaol::gaol sets no language standard, so a CMake project with GCC 9 in C++14 gets no warning for `sqrt(x);`: make GAOL_NODISCARD use the compiler's attribute where [[nodiscard]] is not available (__attribute__((warn_unused_result)) for GCC and Clang, _Check_return_ for Visual C++, [[nodiscard]] from C++17) so that C++11 and C++14 programs get the warning where the compiler can give one; test with GCC 9.4 and Clang 18 in -std=c++11/14/17 that `sqrt(x);` warns (a compile test with WILL_FAIL or PASS_REGULAR_EXPRESSION and -Werror=unused-result, as tests/fp_strict does for other options) and that GAOL's own compilation and the tests emit no new warning; (5) three examples of the manual show true/false where the program prints 1/0 (no std::boolalpha), and nan where it prints -nan: find them in manual/v5/gaol.tex (and in doc/*.md and README.md if they have the same) by running the programs, and correct what is shown to what the programs print (or add std::boolalpha where it reads better: prefer changing the text to the real output; for nan, the sign printed depends on the platform: say what is true), keeping cleanup() at the end of complete programs. manual/v4 is not touched.
""")

point(35, "35-first-program-tutorial", "a first program before the details", "docs", """
A first program before the details. README.md has no C++ code, the first program is at line 92 of doc/using.md, and no document shows an algorithm on intervals. Correction: a ten-line program in README.md that points to examples/, and a short tutorial (image enclosure and subdivision, Newton with % or div_rel, a contractor with the *_rel functions, separation and evaluation), which examples 03, 05, 06 and 07 already contain. Write: (1) in README.md a first program of about ten lines that compiles and prints something instructive about intervals (for instance the dependency problem, x - x, or the enclosure of a function on an interval), preferably kept true by the build: consider making it one of the examples or a test that extracts and compiles the very text of the README program (cheap, and it keeps the README true); it ends with gaol::cleanup(); it links to doc/using.md and examples/; (2) doc/tutorial.md (a new file, linked from the documentation list of README.md and from doc/using.md): short, in this order: enclosing the image of a function with subdivision (example 03), the interval Newton method with % or div_rel (05), a contractor with the *_rel functions (06 and 07: read what each example does first), separation and evaluation; every excerpt is taken from the examples/ programs (which are self-checking and run by the CI) so that the tutorial cannot rot: say which example file each excerpt comes from, or include the complete short programs. All the code shown compiles as shown (compile it as complete programs in a scratch directory with the default build) and complete programs end with gaol::cleanup(). Keep the tone and the English of the existing docs; do not duplicate what doc/using.md says: link to it.
""")

point(36, "36-upward-rounding-effects", "what the upward rounding does to the program", "docs", """
What the upward rounding does to the program, in doc/using.md and in the common errors of the manual, with the table of section 2.8 of the review (examples/examples.md, "2.8 The rounding direction and the rest of the program"): printf, strtod, lrint, round trips through text, TwoSum, and GCC reusing after cleanup() a double computed before. GAOL_PRESERVE_ROUNDING as the way to keep the program's rounding, with its measured cost (4.8 times on x + y, 1.4 to 1.6 times on exp and sin). Verify every claim by running a small program (a table entry you have not seen behave as written is not written): build GAOL both ways (default and -DGAOL_PRESERVE_ROUNDING=ON) and show the outputs; measure the cost figures again only when the machine is quiet (check uptime); if the figures of section 2.8 cannot be reproduced within reason, say what you measured and under which conditions (clang-18, i7-1185G7, no other library, and no GAOL_PRESERVE_ROUNDING otherwise). Do NOT write about the guard and restore API of point n° 23 as if it existed: that point is a separate change; refer to gaol::cleanup() and rnd_keep() as they exist now. Follow the house rules on cleanup() in every complete program. In manual/v5/gaol.tex add the same as an entry of the common errors (the list where the manual describes them) and make sure the manual compiles. Point n° 38 of TODO.md adds other pitfalls to the same list afterwards, on top of your branch.
""")

point(38, "38-manual-pitfalls", "the traps in the common errors of the manual", "docs", """
The traps, in the common errors of the manual (and doc/using.md where a short entry fits): `sqrt(2)` on a number (the C function, not an interval); interval(m - r, m + r) with doubles (the bounds are rounded to nearest, not outward); the empty set that passes all the inclusion tests; the domain without decorations; split() of a canonical interval; / against % in Newton's method; pow(x, 2) taking GAOL's pow when both namespaces (gaol and gaol_ieee1788) are open; a text refused for a non-integer order of nth_root, which throws invalid_action_error and not input_format_error; textToInterval giving the empty set for an ill-formed text; a zero bound written -0, whose sign differs between the SSE2 and the FPU builds (sqr([-1, 2]), interval::zero()). Verify EVERY item by running a small program (an entry you have not seen behave as written is not written; correct the TODO's wording where it is inexact and say so in your report) and show for each the wrong code, its effect and the right code, as short excerpts that compile; complete programs end with gaol::cleanup(). Build both variants, SSE2 and FPU (-DGAOL_SIMD=OFF), for the -0 item. In manual/v5/gaol.tex add them to the list of common errors after the entries of point n° 36 (your base has them). Keep each entry short.
""", chain_note="""
Your base is the branch of point n° 36 (todo-36-upward-rounding-effects), which added entries to the same list of common errors.
""")

point(37, "37-names-table", "a table of names for the users of IBEX, Codac, C-XSC, Boost and IEEE 1788", "docs", """
A table of names for the users of IBEX, Codac, C-XSC, Boost and IEEE 1788 (section 2.3 of the review: examples/examples.md "2.3 Sets, tests and comparisons" and the tables around it), with what <, <= and == mean in each of them: in C-XSC and PROFIL/BIAS, <= is inclusion, and the code ported from them compiles and changes meaning. Where: a new section of doc/using.md, or a new doc/names.md linked from README.md and doc/using.md (choose what fits the structure of the docs), and a short version in the manual (manual/v5/gaol.tex). Content: for each family of operations (the set relations: subset, superset, interior, disjoint, ==; the comparisons; midpoint, radius, width, diameter; hull, intersection, union; bisect and split; empty and universe (entire); the elementary functions whose names differ (sqr, sqrt, pow, pown, rootn/nth_root, atan2, exp2, cbrt...); the reverse functions (IEEE 1788: sqrRev... against GAOL's *_rel); text input/output), the name in GAOL v5 (both namespaces, gaol and gaol_ieee1788), in IEEE 1788-2015, in IBEX, in Codac, in C-XSC, in Boost.Interval and in PROFIL/BIAS where they have one. Do NOT look at IBEX or Codac sources on this machine (the maintainer forbade it: they will follow GAOL): use the review's sections 2.3, 6 and 7, which already hold the comparisons, and public documentation you can fetch for C-XSC, Boost.Interval and PROFIL/BIAS if needed: write only what you can verify, put "-" in a cell rather than guess. Check every GAOL name against the headers (grep) and the claims about <, <=, == by running a small program. Every complete program ends with gaol::cleanup().
""")

point(32, "32-coverage-report", "the coverage report is stale", "docs", """
The coverage report (coverage/README.md) was written on 2026-09-20: its non-executed lines no longer match the sources, which have changed since (one grammar for the string reader, the lexer and the parser made reentrant, the relations possibly_*, certainly_eq and certainly_neq removed). To redo with -DGAOL_COVERAGE=ON and the target coverage, which need gcovr (8.2 is installed). Read how coverage/README.md is made (its structure, its conclusions: which uncovered lines are what and why; the GAOL_COVERAGE section of CMakeLists.txt and the coverage target; .gitignore says only coverage/README.md is kept: the html/css/js/json outputs are not committed), run the coverage build with GCC (the default compiler here, 9.4: gcov must match the compiler; through gcore, -j1: an instrumented build is slow: one build in $SCR/build/..., not in the worktree), then rewrite coverage/README.md: the new figures (per file and in total), the non-executed lines that remain and why they are not executed (unreachable defensive branches, platform-specific code, error paths...), and drop the statements that no longer hold. Verify each statement of the conclusions against the actual report. Say the commit the report was made at (the base of your branch, a2ca992) and the tools (gcc 9.4, gcovr 8.2). Do not commit generated html, js, css or json. doc/differences.md quotes "87 % of the lines of GAOL": do not edit that file (house rules), report the new figure in your ledger fields.
""")

point(31, "31-core-math-upstream", "propose upstream the corrections of the embedded CORE-MATH sources", "high", """
Propose upstream the corrections of the embedded sources: PREPARE, DO NOT SEND. 3rd/README.md lists five changes of the CORE-MATH sources; four are corrections rather than adaptations to GAOL: the ~0ull masks of sinh.c, cosh.c and tanh.c, the signed shifts of cospi.c, the 128-bit shift of asinpi.c, and the 64-bit __builtin_expect of rsqrt.c, which took subnormals for +0 wherever long is 32 bits. A fifth is done in gaol/core_math_port.h rather than in the sources: since its rewrite (upstream commit 6b84457), sin.c calls __builtin_roundeven() without a guard, which GCC lacks before version 10 and GCC 9.4 did not link; the other sources take that builtin only from GCC 10 and Clang 17 and round themselves before (roundeven_finite() of exp.c), which sin.c could do too. Also: the glibc imports the functions of CORE-MATH (glibc 2.41 to 2.44; cosh, sinh and tanh in 2.44) and runs on 32-bit Linux targets, where long is 32 bits too: check whether the glibc copies still have the ~0ul masks and the 64-bit __builtin_expect; if so, the same corrections go to the glibc (libc-alpha, with a Signed-off-by line: no copyright assignment to the FSF since August 2021). Prior art on an OLDER base: the branch origin/todo-review-fixes has 3rd/core-math-patches/ (four patches against upstream master 03720fea of 2026-09-21, and a README saying what each fixes and how it was checked): start from `git -C $MAIN show origin/todo-review-fixes --stat` and its files, check whether they still apply to the CURRENT upstream master (fetch it read-only into $SCR/tmp/: CORE-MATH is at https://gitlab.inria.fr/core-math/core-math; git clone --depth 1 or the web) and to the copies in 3rd/math-core, and redo what is stale. Deliver in the branch: 3rd/core-math-patches/ (the patches against current upstream master, one per defect, in upstream's style, each verified: it applies, it compiles, and the check that shows the defect (a build where long is 32 bits: gcc -m32 if the multilib exists here, else another way to force a 32-bit long, else reasoning: say what you could not check) fails before and passes after), a sixth patch for sin.c's roundeven, a README in that directory, the update of 3rd/README.md pointing to them, the results of the glibc check (fetch glibc's copies read-only, from the sourceware git web interface or the GitHub mirror: which of the defects each copy still has, with file, glibc version or tag, and line) and drafts of the messages to send (one for CORE-MATH's issue tracker or merge request, one for libc-alpha with a Signed-off-by line: use the name and email of `git config` of the repository, never invent; mark them clearly as drafts), in a file of that directory. SENDING is the maintainer's decision: you do not send, post, open an issue or a merge request anywhere, nor push anywhere: you only read. The vendored sources of 3rd/math-core are NOT changed by this point.
""")

point(34, "34-fetchcontent-tag", "the FetchContent recipes fetch GAOL 4", "docs", """
The FetchContent recipes fetch GAOL 4: those of doc/using.md and of the manual, and the `git clone` of doc/building.md, take the master branch of Jordan08/GAOL, which on 2026-09-27 is GAOL 4.2.3, 121 commits behind MATH-CORE: the programs of the documentation do not compile with it, and there is no v5.0.0 tag to pin. Correction: tag v5.0.0, or merge MATH-CORE into master, and write the tag in the recipes. THE TAG (AND ANY MERGE INTO MASTER) IS THE MAINTAINER'S DECISION AND ACTION: you never create a tag, push, or merge anything. What you do: change the recipes (doc/using.md, doc/building.md, manual/v5/gaol.tex, README.md, tests/fetch_content if it documents one; grep the whole tree for GIT_TAG, git clone, FetchContent, `master`) to name the tag v5.0.0 (GIT_TAG v5.0.0, git clone --branch v5.0.0 ...), so that the recipes are right as soon as the maintainer tags the release; verify the recipes locally WITHOUT touching the maintainer's repository or GitHub: make a local bare clone in $SCR/tmp/ of the branch you are on, create the tag v5.0.0 in that clone only, and run the recipe of the docs (a tiny CMake project with FetchContent_Declare(GIT_REPOSITORY file://<the local clone> GIT_TAG v5.0.0) and the programs of the docs) to prove that the text of the recipe is right; check the version macros (5.0.0) that the fetched tree gives. Say in your report exactly what the maintainer has to do before merging this branch (create the tag v5.0.0 on the right commit) and the alternative (merging MATH-CORE into master). Where a sentence about a development version is useful, GIT_TAG can name the branch.
""")

# ---------------------------------------------------------------------------------------------------------------
if __name__ == "__main__":
    import points_w4
    points_w4.define(point, P)
    body = open(SCR + "/todo_body.js").read()
    marker = "\nconst SCR = "
    k = body.index(marker)
    # `export const meta` must stay the first statement: the table goes right after it
    js = body[:k] + "\n\nconst POINTS = " + json.dumps(P, indent=1) + "\n" + body[k:]
    open(SCR + "/todo_implement_w4.js", "w").write(js)
    print("points:", sorted(P, key=str), "->", SCR + "/todo_implement_w4.js", len(js), "bytes")
